// ═══════════════════════════════════════════════════════════
// CATÁLOGO DE ITENS DO ALMOXARIFADO — SEMCAS
// Gerado automaticamente · Embutido no JS · Sem Firebase
// 967 aliases · 447 itens únicos · 6 categorias
// ═══════════════════════════════════════════════════════════

// ── Normalização (sem acento, maiúsculo, espaço único) ─────
function _rmac(s){
  return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/\s+/g," ").trim();
}

// ── Mapa: nome_original_normalizado → [nome_correto, categoria] ─
const ITEMS_ALIASES = {
  "ABSORVENTE": ["ABSORVENTE", "Material de Higiene Pessoal"],
  "ABSORVENTE FEMININO": ["ABSORVENTE", "Material de Higiene Pessoal"],
  "ACHOCOLATADO": ["ACHOCOLATADO EM PÓ", "Alimentos"],
  "ACHOCOLATADO EM PO": ["ACHOCOLATADO EM PÓ", "Alimentos"],
  "ACUCAR": ["AÇÚCAR", "Alimentos"],
  "ACUCAR REFINADO": ["AÇÚCAR REFINADO", "Alimentos"],
  "AFINETE P/ MURAL (PERCEVEJO)": ["PERCEVEJO PARA MURAL", "Material de Expediente"],
  "AGUA SANITARIA": ["ÁGUA SANITÁRIA", "Material de Limpeza"],
  "AGULHA DE CROCHE": ["AGULHA DE CROCHÊ", "Atividades/Convivência"],
  "ALCOOL": ["ÁLCOOL LÍQUIDO", "Material de Limpeza"],
  "ALCOOL (GEL OU LIQUIDO)": ["ÁLCOOL EM GEL", "Material de Limpeza"],
  "ALCOOL 70": ["ÁLCOOL LÍQUIDO 70%", "Material de Limpeza"],
  "ALCOOL EM GEL": ["ÁLCOOL EM GEL", "Material de Limpeza"],
  "ALCOOL EM GEL OU LIQUIDO": ["ÁLCOOL EM GEL", "Material de Limpeza"],
  "ALCOOL ETILILICO HIDRATADO 70": ["ÁLCOOL LÍQUIDO 70%", "Material de Limpeza"],
  "ALCOOL GEL": ["ÁLCOOL EM GEL", "Material de Limpeza"],
  "ALCOOL GEL 70": ["ÁLCOOL EM GEL 70%", "Material de Limpeza"],
  "ALCOOL LIQ": ["ÁLCOOL LÍQUIDO", "Material de Limpeza"],
  "ALCOOL LIQUIDO": ["ÁLCOOL LÍQUIDO", "Material de Limpeza"],
  "ALCOOL LIQUIDO 70%": ["ÁLCOOL LÍQUIDO 70%", "Material de Limpeza"],
  "ALCOOL LIQUIDO OU GEL": ["ÁLCOOL LÍQUIDO", "Material de Limpeza"],
  "ALFABETO DE LETRA(BRINQUEDO LUDICO)": ["JOGO DE ALFABETO", "Atividades/Convivência"],
  "ALMODADA CARIMBO": ["ALMOFADA DE CARIMBO", "Atividades/Convivência"],
  "ALMOFADA DE CARIMBO": ["ALMOFADA DE CARIMBO", "Atividades/Convivência"],
  "ALMOFADA PARA CARIMBO": ["ALMOFADA DE CARIMBO", "Atividades/Convivência"],
  "AMIDO DE MILHO": ["AMIDO DE MILHO", "Alimentos"],
  "APAGADOR DE QUADRO BRANCO": ["APAGADOR DE QUADRO BRANCO", "Material de Expediente"],
  "APITO": ["APITO", "Atividades/Convivência"],
  "APONTADOR": ["APONTADOR", "Material de Expediente"],
  "AROMATIZADOR DE AMBIENTE (BOM AR)": ["BOM AR", "Material de Limpeza"],
  "AROMATIZADOR DE AR": ["BOM AR", "Material de Limpeza"],
  "AROMATIZANTE": ["BOM AR", "Material de Limpeza"],
  "ARROZ": ["ARROZ", "Alimentos"],
  "ARROZ BRANCO": ["ARROZ", "Alimentos"],
  "ARROZ(LANCHE PCF": ["ARROZ", "Alimentos"],
  "ATA": ["LIVRO DE ATA", "Material de Expediente"],
  "AVEIA": ["AVEIA EM FLOCOS", "Alimentos"],
  "AVEIA EM FLOCO": ["AVEIA EM FLOCOS", "Alimentos"],
  "AVENTAL DE PLASTICO": ["AVENTAL PLÁSTICO", "Material de Limpeza"],
  "BALAO": ["BALÃO", "Atividades/Convivência"],
  "BALAO (VERMELHO/AZUL/AMARELO/VERDE/BRANCO)": ["BALÃO CORES VARIADAS", "Atividades/Convivência"],
  "BALAO AMARELO": ["BALÃO AMARELO", "Atividades/Convivência"],
  "BALAO AZUL": ["BALÃO AZUL", "Atividades/Convivência"],
  "BALAO BRANCO": ["BALÃO BRANCO", "Atividades/Convivência"],
  "BALAO COLORIDO": ["BALÃO CORES VARIADAS", "Atividades/Convivência"],
  "BALAO CORE VAIRADA": ["BALÃO CORES VARIADAS", "Atividades/Convivência"],
  "BALAO CORE VARIADA": ["BALÃO CORES VARIADAS", "Atividades/Convivência"],
  "BALAO CORES VARIADAS": ["BALÃO CORES VARIADAS", "Atividades/Convivência"],
  "BALAO NAS CORE AMARELO": ["BALÃO AMARELO", "Atividades/Convivência"],
  "BALAO NAS CORE LARANJA": ["BALÃO LARANJA", "Atividades/Convivência"],
  "BALAO VERDE": ["BALÃO VERDE", "Atividades/Convivência"],
  "BALAO VERMELHO": ["BALÃO VERMELHO", "Atividades/Convivência"],
  "BALDE": ["BALDE", "Material de Limpeza"],
  "BALDE 20 LITRO": ["BALDE 20L", "Material de Limpeza"],
  "BALDE 30 LITRO": ["BALDE 30L", "Material de Limpeza"],
  "BALDE 30 LITROS": ["BALDE 30L", "Material de Limpeza"],
  "BALDE GRANDE 50 LITRO": ["BALDE 50L", "Material de Limpeza"],
  "BALDE GRANDE 50 LITROS": ["BALDE 50L", "Material de Limpeza"],
  "BALDE P/LIMPEZA": ["BALDE", "Material de Limpeza"],
  "BALDE PEQUENO": ["BALDE 20L", "Material de Limpeza"],
  "BALDES": ["BALDE", "Material de Limpeza"],
  "BALDES 20 LITROS": ["BALDE 20L", "Material de Limpeza"],
  "BALDES P/LIMPEZA": ["BALDE", "Material de Limpeza"],
  "BALOES": ["BALÃO CORES VARIADAS", "Atividades/Convivência"],
  "BALOES AMARELO, BRANCO, LARANJA": ["BALÃO CORES VARIADAS", "Atividades/Convivência"],
  "BAMBOLE": ["BAMBOLÊ", "Atividades/Convivência"],
  "BANDEJA PARA ORGANIZAR PAPEL": ["BANDEJA PARA PAPEL", "Material de Expediente"],
  "BARBANTE DE ALGODAO": ["BARBANTE", "Atividades/Convivência"],
  "BARBANTE DE CIZAL": ["BARBANTE", "Atividades/Convivência"],
  "BASTAO DE COLA QUENTE": ["BASTÃO DE COLA QUENTE", "Atividades/Convivência"],
  "BASTAO DE COLA QUENTE FINO": ["BASTÃO DE COLA QUENTE", "Atividades/Convivência"],
  "BASTAO PARA COLA QUENTE": ["BASTÃO DE COLA QUENTE", "Atividades/Convivência"],
  "BAYGON": ["INSETICIDA", "Material de Limpeza"],
  "BISCOITO": ["BISCOITO DOCE", "Alimentos"],
  "BISCOITO (DOCE/SALGADO)": ["BISCOITO DOCE / BISCOITO ÁGUA E SAL", "Alimentos"],
  "BISCOITO AGUA": ["BISCOITO ÁGUA E SAL", "Alimentos"],
  "BISCOITO AGUA E SAL": ["BISCOITO ÁGUA E SAL", "Alimentos"],
  "BISCOITO CREAM CRACKER": ["BISCOITO ÁGUA E SAL", "Alimentos"],
  "BISCOITO CREEM CRACKER": ["BISCOITO ÁGUA E SAL", "Alimentos"],
  "BISCOITO DOCE": ["BISCOITO DOCE", "Alimentos"],
  "BISCOITO DOCE/SALGADO": ["BISCOITO DOCE / BISCOITO ÁGUA E SAL", "Alimentos"],
  "BISCOITO MARIA": ["BISCOITO MARIA", "Alimentos"],
  "BISCOITO REHEADO": ["BISCOITO RECHEADO", "Alimentos"],
  "BISCOITO SAL": ["BISCOITO ÁGUA E SAL", "Alimentos"],
  "BISCOITO SALGADO": ["BISCOITO ÁGUA E SAL", "Alimentos"],
  "BISCOITO/DOCE/SALGADO": ["BISCOITO DOCE / BISCOITO ÁGUA E SAL", "Alimentos"],
  "BISCOITOS DE POVILHO": ["BISCOITO DE POLVILHO", "Alimentos"],
  "BISOITO SALGADO": ["BISCOITO ÁGUA E SAL", "Alimentos"],
  "BLOCO DE ANOTACAO": ["BLOCO DE NOTAS", "Material de Expediente"],
  "BLOCO DE NOTAS": ["BLOCO DE NOTAS", "Material de Expediente"],
  "BLOCO DE RECADO": ["BLOCO DE NOTAS", "Material de Expediente"],
  "BLOCO PARA RECADO (OFF STICK)": ["POST-IT", "Material de Expediente"],
  "BLOCO PARA RECADO (POST-IT)": ["POST-IT", "Material de Expediente"],
  "BOLA CAMPO": ["BOLA DE FUTEBOL DE CAMPO", "Atividades/Convivência"],
  "BOLA DE FUTSAL": ["BOLA DE FUTSAL", "Atividades/Convivência"],
  "BOLA DE QUEIMADO": ["BOLA DE QUEIMADO", "Atividades/Convivência"],
  "BOLA IOIO COM LUZES DIVERIDA/BRILHO NO ESCURO": ["IOIÔ COM LUZES", "Atividades/Convivência"],
  "BOLACHA": ["BISCOITO DOCE", "Alimentos"],
  "BOLACHA DOCE": ["BISCOITO DOCE", "Alimentos"],
  "BOLACHA SALGADA": ["BISCOITO ÁGUA E SAL", "Alimentos"],
  "BOLACHA SLGADA": ["BISCOITO ÁGUA E SAL", "Alimentos"],
  "BOLINHA PILATE": ["BOLINHA PILATES", "Atividades/Convivência"],
  "BOM AR": ["BOM AR", "Material de Limpeza"],
  "BOM BRIL": ["PALHA DE AÇO", "Material de Limpeza"],
  "BOMBRIL": ["PALHA DE AÇO", "Material de Limpeza"],
  "BOMBRIL ESPONJA DE ACO": ["PALHA DE AÇO", "Material de Limpeza"],
  "BORRACHA": ["BORRACHA", "Material de Expediente"],
  "BORRACHA BICOLOR": ["BORRACHA BICOLOR", "Material de Expediente"],
  "BUCHA DE LAVAR LOUCA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "CADEADO": ["CADEADO", "Material de Expediente"],
  "CADERNO ATA": ["LIVRO DE ATA", "Material de Expediente"],
  "CADERNO DE ATA": ["LIVRO DE ATA", "Material de Expediente"],
  "CADERNO DE ATA FINO": ["LIVRO DE ATA FINO", "Material de Expediente"],
  "CADERNO DE ATA GROSSO": ["LIVRO DE ATA GROSSO", "Material de Expediente"],
  "CADERNO DE ATAS": ["LIVRO DE ATA", "Material de Expediente"],
  "CADERNO DE BROCHURA": ["CADERNO BROCHURA", "Material de Expediente"],
  "CADERNO DE CAPA DURA": ["LIVRO DE ATA", "Material de Expediente"],
  "CADERNO DE DESENHO": ["CADERNO DE DESENHO", "Atividades/Convivência"],
  "CADERNO GRANDE": ["CADERNO UNIVERSITÁRIO", "Material de Expediente"],
  "CADERNO GRANDE (CAPA DURA)": ["LIVRO DE ATA", "Material de Expediente"],
  "CAFE": ["CAFÉ", "Alimentos"],
  "CAIXA ARQUIVO": ["CAIXA ARQUIVO MORTO", "Material de Expediente"],
  "CAIXA ARQUIVO PLASTICA": ["CAIXA ARQUIVO MORTO", "Material de Expediente"],
  "CAIXA CANETA AZUL": ["CANETA AZUL", "Material de Expediente"],
  "CAIXA DE BOMBOM DE CHOCOLATE": ["BOMBOM DE CHOCOLATE", "Alimentos"],
  "CAIXA DE FOSFORO": ["FÓSFORO", "Material de Expediente"],
  "CAIXA DE MASCARA DESCARTAVEL": ["MÁSCARA DESCARTÁVEL", "Material Descartável"],
  "CALABRESA": ["CALABRESA EM LATA", "Alimentos"],
  "CANETA": ["CANETA", "Material de Expediente"],
  "CANETA AZUL": ["CANETA AZUL", "Material de Expediente"],
  "CANETA AZUL /PRETA": ["CANETA AZUL / CANETA PRETA", "Material de Expediente"],
  "CANETA AZUL E PRETA": ["CANETA AZUL / CANETA PRETA", "Material de Expediente"],
  "CANETA AZUL OU PRETA": ["CANETA AZUL / CANETA PRETA", "Material de Expediente"],
  "CANETA AZUL,PRETA ,VERMELHA": ["CANETA AZUL / CANETA PRETA / CANETA VERMELHA", "Material de Expediente"],
  "CANETA ESFEROGRAFICA AZUL": ["CANETA AZUL", "Material de Expediente"],
  "CANETA HIDROCOR": ["CANETINHA HIDROCOR", "Atividades/Convivência"],
  "CANETA MARCADORA": ["MARCADOR PERMANENTE", "Material de Expediente"],
  "CANETA PRETA": ["CANETA PRETA", "Material de Expediente"],
  "CANETA PRETA AZUL": ["CANETA AZUL / CANETA PRETA", "Material de Expediente"],
  "CANETA PRETA E AZUL": ["CANETA PRETA / CANETA AZUL", "Material de Expediente"],
  "CANETA PRETA/ AZUL": ["CANETA PRETA / CANETA AZUL", "Material de Expediente"],
  "CANETA VERMELHA": ["CANETA VERMELHA", "Material de Expediente"],
  "CANETAS": ["CANETA", "Material de Expediente"],
  "CANETAS (PRETA, AZUL E VERMELHA)": ["CANETA AZUL / CANETA PRETA / CANETA VERMELHA", "Material de Expediente"],
  "CANETAS AZUIS": ["CANETA AZUL", "Material de Expediente"],
  "CANETAS AZUL": ["CANETA AZUL", "Material de Expediente"],
  "CANETAS PRETAS": ["CANETA PRETA", "Material de Expediente"],
  "CANJICA DE MILHO BRANCO": ["CANJICA DE MILHO BRANCO", "Alimentos"],
  "CAPA DE PROCESSO": ["CAPA DE PROCESSO", "Material de Expediente"],
  "CARNE ENLATADA": ["CARNE ENLATADA", "Alimentos"],
  "CARTOLINA - AMARELO, VERDE, ROSA, AZUL, BRANCO": ["CARTOLINA CORES VARIADAS", "Atividades/Convivência"],
  "CARTOLINA CARTAO": ["CARTOLINA", "Atividades/Convivência"],
  "CARTOLINA CORE VARIADA": ["CARTOLINA CORES VARIADAS", "Atividades/Convivência"],
  "CARTOLINA CORES VARIADAS": ["CARTOLINA CORES VARIADAS", "Atividades/Convivência"],
  "CARTOLINA GRANDE": ["CARTOLINA", "Atividades/Convivência"],
  "CARTOLINA GUACHE (CORES DIVERSAS)": ["CARTOLINA CORES VARIADAS", "Atividades/Convivência"],
  "CARTOLINA ROSA": ["CARTOLINA ROSA", "Atividades/Convivência"],
  "CARTOLINA VARIADO": ["CARTOLINA CORES VARIADAS", "Atividades/Convivência"],
  "CARTOLINA VERDE": ["CARTOLINA VERDE", "Atividades/Convivência"],
  "CESTO DE LIXO": ["CESTO DE LIXO", "Material de Limpeza"],
  "CESTO DE LIXO COM PEDAL": ["CESTO DE LIXO COM PEDAL", "Material de Limpeza"],
  "CESTO DE LIXO COM TAMPA": ["CESTO DE LIXO COM TAMPA", "Material de Limpeza"],
  "CESTO DE LIXO COM TAMPA COM PEDAL": ["CESTO DE LIXO COM PEDAL", "Material de Limpeza"],
  "CESTO DE LIXO GRANDE": ["CESTO DE LIXO GRANDE", "Material de Limpeza"],
  "CESTO DE LIXO PEQUENO": ["CESTO DE LIXO PEQUENO", "Material de Limpeza"],
  "CESTO PARA LIXO": ["CESTO DE LIXO", "Material de Limpeza"],
  "CESTO PARA LIXO PEQUENO": ["CESTO DE LIXO PEQUENO", "Material de Limpeza"],
  "CESTO PEQUENO PARA LIXO": ["CESTO DE LIXO PEQUENO", "Material de Limpeza"],
  "CHA EM CAIXA DE CAMOMILA": ["CHÁ DE CAMOMILA", "Alimentos"],
  "CHA EM CAIXA DE CIDREIRA": ["CHÁ DE CIDREIRA", "Alimentos"],
  "CHAMEQUINHO PAPEL A4 COLORIDO": ["RESMA DE PAPEL A4 COLORIDO", "Material de Expediente"],
  "CHAMEX": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "CHAMEX PAPEL A4 COLORIDO": ["RESMA DE PAPEL A4 COLORIDO", "Material de Expediente"],
  "CHAMEX PAPEL SULFITE A4": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "CLIPE 4/0": ["CLIPS Nº 4/0", "Material de Expediente"],
  "CLIPE TAMANHO 2/0": ["CLIPS Nº 2/0", "Material de Expediente"],
  "CLIPES": ["CLIPS", "Material de Expediente"],
  "CLIPES TAMANHO 2/0": ["CLIPS Nº 2/0", "Material de Expediente"],
  "CLIPS": ["CLIPS", "Material de Expediente"],
  "CLIPS 04": ["CLIPS Nº 4/0", "Material de Expediente"],
  "CLIPS 08": ["CLIPS Nº 8/0", "Material de Expediente"],
  "CLIPS 3/0": ["CLIPS Nº 3/0", "Material de Expediente"],
  "CLIPS GRANDE": ["CLIPS Nº 8/0", "Material de Expediente"],
  "CLIPS MEDIO": ["CLIPS Nº 4/0", "Material de Expediente"],
  "CLIPS N 10/0": ["CLIPS Nº 10/0", "Material de Expediente"],
  "CLIPS N 2/0": ["CLIPS Nº 2/0", "Material de Expediente"],
  "CLIPS N 3/0": ["CLIPS Nº 3/0", "Material de Expediente"],
  "CLIPS N 4/0": ["CLIPS Nº 4/0", "Material de Expediente"],
  "CLIPS N 5/0": ["CLIPS Nº 5/0", "Material de Expediente"],
  "CLIPS N 50,36,25": ["CLIPS", "Material de Expediente"],
  "CLIPS N 503625/0": ["CLIPS", "Material de Expediente"],
  "CLIPS N 6": ["CLIPS Nº 6/0", "Material de Expediente"],
  "CLIPS N 6/0": ["CLIPS Nº 6/0", "Material de Expediente"],
  "CLIPS N 8/0": ["CLIPS Nº 8/0", "Material de Expediente"],
  "CLIPS PARA PAPEL": ["CLIPS", "Material de Expediente"],
  "CLIPS PEQUENO": ["CLIPS Nº 2/0", "Material de Expediente"],
  "COADOR DE CAFE": ["COADOR DE CAFÉ", "Alimentos"],
  "COLA ( ISOPOR )": ["COLA DE ISOPOR", "Atividades/Convivência"],
  "COLA BASTAO": ["COLA BASTÃO", "Material de Expediente"],
  "COLA BLASCOPLAST TUBO GRANDE": ["COLA DE CONTATO (BRASCOLA)", "Material de Limpeza"],
  "COLA BRANCA": ["COLA BRANCA", "Material de Expediente"],
  "COLA BRASCOPLAST": ["COLA DE CONTATO (BRASCOLA)", "Material de Limpeza"],
  "COLA C/ GLITTER DOURADA": ["COLA COM GLITTER DOURADO", "Atividades/Convivência"],
  "COLA COLORIDA": ["COLA COM GLITTER", "Atividades/Convivência"],
  "COLA COLORIDA (CORES VARIADAS)": ["COLA COM GLITTER", "Atividades/Convivência"],
  "COLA COM GLITER": ["COLA COM GLITTER", "Atividades/Convivência"],
  "COLA DE CONTATO": ["COLA DE CONTATO", "Material de Limpeza"],
  "COLA DE EVA": ["COLA PARA EVA", "Atividades/Convivência"],
  "COLA DE ISOPOR": ["COLA DE ISOPOR", "Atividades/Convivência"],
  "COLA DE SILICONE": ["COLA DE SILICONE", "Atividades/Convivência"],
  "COLA EM BASTAO": ["COLA BASTÃO", "Material de Expediente"],
  "COLA EVA": ["COLA PARA EVA", "Atividades/Convivência"],
  "COLA GLITER": ["COLA COM GLITTER", "Atividades/Convivência"],
  "COLA GLITER COLORIDA": ["COLA COM GLITTER", "Atividades/Convivência"],
  "COLA PARA E.V.A": ["COLA PARA EVA", "Atividades/Convivência"],
  "COLA PARA EVA": ["COLA PARA EVA", "Atividades/Convivência"],
  "COLA PARA TECIDO": ["COLA PARA TECIDO", "Atividades/Convivência"],
  "COLA QUENTE": ["COLA QUENTE", "Atividades/Convivência"],
  "COLA QUENTE (OFICINA PCF)": ["COLA QUENTE", "Atividades/Convivência"],
  "COLA QUENTE BASTAO": ["COLA QUENTE", "Atividades/Convivência"],
  "COLA QUENTE PEQUENA": ["COLA QUENTE", "Atividades/Convivência"],
  "COLA SPRAY": ["COLA SPRAY", "Material de Expediente"],
  "COLA TEC BOND": ["SUPER BONDER", "Material de Limpeza"],
  "COLA TEK BOND": ["SUPER BONDER", "Material de Limpeza"],
  "COLHER DESCARTAVEIS": ["COLHER DESCARTÁVEL", "Material Descartável"],
  "COLHER DESCARTAVEL": ["COLHER DESCARTÁVEL", "Material Descartável"],
  "COLHERES": ["COLHER DESCARTÁVEL", "Material Descartável"],
  "COLHERES DESCARTAVEIS": ["COLHER DESCARTÁVEL", "Material Descartável"],
  "COPO DESCARTAVEL PARA AGUA": ["COPO DESCARTÁVEL PARA ÁGUA", "Material Descartável"],
  "COPO DESCARTAVEL PARA CAFE": ["COPO DESCARTÁVEL PARA CAFÉ", "Material Descartável"],
  "COPOS PARA AGUA": ["COPO DESCARTÁVEL PARA ÁGUA", "Material Descartável"],
  "COPOS PARA CAFE": ["COPO DESCARTÁVEL PARA CAFÉ", "Material Descartável"],
  "CORRETIVO": ["CORRETIVO", "Material de Expediente"],
  "CORRETIVOS": ["CORRETIVO", "Material de Expediente"],
  "CREME DE LEITE": ["CREME DE LEITE", "Alimentos"],
  "CREME DENTAL": ["CREME DENTAL", "Material de Higiene Pessoal"],
  "CREMOGEMA": ["CREMOGEMA", "Alimentos"],
  "CREPON AMARELO": ["PAPEL CREPOM AMARELO", "Atividades/Convivência"],
  "CUSCU FLOCAO DE ARROZ": ["CUSCUZ DE ARROZ", "Alimentos"],
  "CUSCUZ": ["CUSCUZ", "Alimentos"],
  "CUSCUZ DE ARROZ": ["CUSCUZ DE ARROZ", "Alimentos"],
  "CUSCUZ DE MILHO": ["CUSCUZ DE MILHO", "Alimentos"],
  "CUZCUZ": ["CUSCUZ", "Alimentos"],
  "DAMAS": ["JOGO DE DAMAS", "Atividades/Convivência"],
  "DESEMGORDURANTE": ["DESENGRAXANTE", "Material de Limpeza"],
  "DESIFETANTE": ["DESINFETANTE", "Material de Limpeza"],
  "DESIFETANTE BANHEIRO": ["DESINFETANTE", "Material de Limpeza"],
  "DESINFETANTE": ["DESINFETANTE", "Material de Limpeza"],
  "DESINFETANTE BANHEIRO": ["DESINFETANTE", "Material de Limpeza"],
  "DESINFETANTE P/CHAO": ["DESINFETANTE PARA CHÃO", "Material de Limpeza"],
  "DESODOR/PEDRA PRA SANITORIO": ["PEDRA SANITÁRIA", "Material de Limpeza"],
  "DETERGENTE": ["DETERGENTE LAVA-LOUÇA", "Material de Limpeza"],
  "DETERGENTE DE PIA": ["DETERGENTE LAVA-LOUÇA", "Material de Limpeza"],
  "DETERGENTE DETERGENTE LAVA-LOUCA": ["DETERGENTE LAVA-LOUÇA", "Material de Limpeza"],
  "DETERGENTE LAVA LOUCA": ["DETERGENTE LAVA-LOUÇA", "Material de Limpeza"],
  "DETERGENTE LAVA-LOUCA 500ML": ["DETERGENTE LAVA-LOUÇA", "Material de Limpeza"],
  "DETERGENTE LIQUIDO": ["DETERGENTE LAVA-LOUÇA", "Material de Limpeza"],
  "DETERGENTE MULTIUSO": ["DETERGENTE MULTIUSO", "Material de Limpeza"],
  "DETERGENTE NEUTRO 500 ML": ["DETERGENTE LAVA-LOUÇA", "Material de Limpeza"],
  "DETERGENTE PIA": ["DETERGENTE LAVA-LOUÇA", "Material de Limpeza"],
  "DISPENSER DE SABONETE LIQUIDO": ["DISPENSER DE SABONETE", "Material de Higiene Pessoal"],
  "E.V.A AMARELO": ["EVA AMARELO", "Atividades/Convivência"],
  "E.V.A AMARELO E LARANJA": ["EVA CORES VARIADAS", "Atividades/Convivência"],
  "E.V.A AZUL, ROSA, VERMELHO, AMARELO": ["EVA CORES VARIADAS", "Atividades/Convivência"],
  "E.V.A COM GLITER AMARELO, VERMELHO, ROSA": ["EVA COM GLITTER CORES VARIADAS", "Atividades/Convivência"],
  "E.V.A COM GLITER BRANCO": ["EVA COM GLITTER BRANCO", "Atividades/Convivência"],
  "E.V.A COM GLITER ROSA": ["EVA COM GLITTER ROSA", "Atividades/Convivência"],
  "E.V.A VARIA CORE": ["EVA CORES VARIADAS", "Atividades/Convivência"],
  "E.V.A VARIADA CORE": ["EVA CORES VARIADAS", "Atividades/Convivência"],
  "E.V.A VERMELHO": ["EVA VERMELHO", "Atividades/Convivência"],
  "E.V.A. - CORE SORTIDA C/ GLITER": ["EVA COM GLITTER CORES VARIADAS", "Atividades/Convivência"],
  "E.V.A. - CORES SORTIDAS C/ GLITER": ["EVA COM GLITTER CORES VARIADAS", "Atividades/Convivência"],
  "ELASTEC": ["LIGA ELÁSTICA", "Material de Expediente"],
  "ELASTICO": ["LIGA ELÁSTICA", "Material de Expediente"],
  "ELASTICO LATEX(LIGA)": ["LIGA ELÁSTICA", "Material de Expediente"],
  "ENVELOPE": ["ENVELOPE", "Material de Expediente"],
  "ENVELOPE A4": ["ENVELOPE A4", "Material de Expediente"],
  "ENVELOPE GRANDE": ["ENVELOPE GRANDE", "Material de Expediente"],
  "ENVELOPE OFICIO": ["ENVELOPE OFÍCIO", "Material de Expediente"],
  "ENVELOPES A4": ["ENVELOPE A4", "Material de Expediente"],
  "ENVELOPES DOS GRANDES": ["ENVELOPE GRANDE", "Material de Expediente"],
  "ESCACELA FINA": ["ESCARCELA FINA", "Material de Expediente"],
  "ESCANCELAS FINAS": ["ESCARCELA FINA", "Material de Expediente"],
  "ESCANCELAS GROSSAS": ["ESCARCELA GROSSA", "Material de Expediente"],
  "ESCARCELA": ["ESCARCELA", "Material de Expediente"],
  "ESCARCELA DE PAPEL": ["ESCARCELA", "Material de Expediente"],
  "ESCARCELA DE PLASTICO FINA": ["ESCARCELA PLÁSTICA FINA", "Material de Expediente"],
  "ESCARCELA FINA": ["ESCARCELA FINA", "Material de Expediente"],
  "ESCARCELA GROSSA": ["ESCARCELA GROSSA", "Material de Expediente"],
  "ESCARCELA PLASTICA": ["ESCARCELA PLÁSTICA", "Material de Expediente"],
  "ESCARCELAS": ["ESCARCELA", "Material de Expediente"],
  "ESCARCELAS (GROSSA E FINA)": ["ESCARCELA", "Material de Expediente"],
  "ESCARCELAS DE PLASTICO FINA": ["ESCARCELA PLÁSTICA FINA", "Material de Expediente"],
  "ESCASCELAS -3 DIA 23/04/26": ["ESCARCELA", "Material de Expediente"],
  "ESCOVA MULTIUSO LAVANDERIA": ["ESCOVA DE LAVAR", "Material de Limpeza"],
  "ESCOVA SANITARIA": ["ESCOVA SANITÁRIA", "Material de Limpeza"],
  "ESCOVAO": ["ESCOVÃO", "Material de Limpeza"],
  "ESCOVINHA SANITARIA": ["ESCOVA SANITÁRIA", "Material de Limpeza"],
  "ESPANADOR": ["ESPANADOR", "Material de Limpeza"],
  "ESPONJA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA 3 M": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA DE ACO": ["PALHA DE AÇO", "Material de Limpeza"],
  "ESPONJA DE DETERGENTE LAVA-LOUCA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA DE LAVA LOUCA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA DE LAVAR LOUCA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA DE LAVAR LOUCAS": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA DE LAVRA LOUCAS": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA DE LOUCA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA DE PIA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA DETERGENTE LAVA-LOUCA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA DUPLA FACE": ["ESPONJA DUPLA FACE", "Material de Limpeza"],
  "ESPONJA LAVA LOUCA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA MULTIUSO DUPLA FACE VERDE": ["ESPONJA DUPLA FACE", "Material de Limpeza"],
  "ESPONJA P/ LAVAR LOUCA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA P/ PIA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA PARA LAVAR LOUCA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESPONJA PARA LOUCA": ["ESPONJA DE LAVAR LOUÇA", "Material de Limpeza"],
  "ESTILETE": ["ESTILETE", "Material de Expediente"],
  "ESTILETE LARGO": ["ESTILETE LARGO", "Material de Expediente"],
  "ESTRATO DE GRAMPOS": ["EXTRATOR DE GRAMPOS", "Material de Expediente"],
  "ETIQUETA AUTO ADESIVA": ["ETIQUETA ADESIVA", "Material de Expediente"],
  "ETIQUETA PARA PASTA SUSPENSA": ["ETIQUETA PARA PASTA SUSPENSA", "Material de Expediente"],
  "EVA": ["EVA", "Atividades/Convivência"],
  "EVA (BEGE) OFICINA PCF": ["EVA BEGE", "Atividades/Convivência"],
  "EVA (BRANCO) OFICINA PCF": ["EVA BRANCO", "Atividades/Convivência"],
  "EVA (PRETO) OFICINA PCF": ["EVA PRETO", "Atividades/Convivência"],
  "EVA (VERMELHO) OFI.CINA PCF": ["EVA VERMELHO", "Atividades/Convivência"],
  "EVA AMARELO": ["EVA AMARELO", "Atividades/Convivência"],
  "EVA AZUL": ["EVA AZUL", "Atividades/Convivência"],
  "EVA C/ GLITTE VARIADO": ["EVA COM GLITTER CORES VARIADAS", "Atividades/Convivência"],
  "EVA COM GLITER DOURADO": ["EVA COM GLITTER DOURADO", "Atividades/Convivência"],
  "EVA COM GLITER PRATA": ["EVA COM GLITTER PRATA", "Atividades/Convivência"],
  "EVA COM GLITER VERDE": ["EVA COM GLITTER VERDE", "Atividades/Convivência"],
  "EVA COM GLITER VERMELHO": ["EVA COM GLITTER VERMELHO", "Atividades/Convivência"],
  "EVA COR AMARELA": ["EVA AMARELO", "Atividades/Convivência"],
  "EVA COR DE ROSA": ["EVA ROSA", "Atividades/Convivência"],
  "EVA COR LARANJA": ["EVA LARANJA", "Atividades/Convivência"],
  "EVA COR ROSO": ["EVA ROSA", "Atividades/Convivência"],
  "EVA CORE VARIADA": ["EVA CORES VARIADAS", "Atividades/Convivência"],
  "EVA CORE VARIADAS- (OFIC. SCFV)": ["EVA CORES VARIADAS", "Atividades/Convivência"],
  "EVA CORES VARIADAS": ["EVA CORES VARIADAS", "Atividades/Convivência"],
  "EVA CORES VARIADAS- (OFIC. SCFV)": ["EVA CORES VARIADAS", "Atividades/Convivência"],
  "EVA DOURADO C/ GLITTER": ["EVA COM GLITTER DOURADO", "Atividades/Convivência"],
  "EVA LARANJA": ["EVA LARANJA", "Atividades/Convivência"],
  "EVA NAS CORE AMARELO": ["EVA AMARELO", "Atividades/Convivência"],
  "EVA NAS CORE LARANJA": ["EVA LARANJA", "Atividades/Convivência"],
  "EVA ROSA": ["EVA ROSA", "Atividades/Convivência"],
  "EVA VARIADO": ["EVA CORES VARIADAS", "Atividades/Convivência"],
  "EVA VARIADOS COM GLITER": ["EVA COM GLITTER CORES VARIADAS", "Atividades/Convivência"],
  "EVA VERDE": ["EVA VERDE", "Atividades/Convivência"],
  "EVA VERDE C/ GLITTER": ["EVA COM GLITTER VERDE", "Atividades/Convivência"],
  "EVA VERMELHO": ["EVA VERMELHO", "Atividades/Convivência"],
  "EVA VERMELHO C/ GLITTER": ["EVA COM GLITTER VERMELHO", "Atividades/Convivência"],
  "EXTRATO DE TOMATE": ["EXTRATO DE TOMATE", "Alimentos"],
  "EXTRATOR DE GRAMPO": ["EXTRATOR DE GRAMPOS", "Material de Expediente"],
  "EXTRATOR DE GRAMPO TIPO ESPATULA": ["EXTRATOR DE GRAMPOS TIPO ESPÁTULA", "Material de Expediente"],
  "FARINHA AMARELA": ["FARINHA DE MILHO", "Alimentos"],
  "FARINHA BRANCA": ["FARINHA BRANCA", "Alimentos"],
  "FARINHA DE TRIGO": ["FARINHA DE TRIGO", "Alimentos"],
  "FARINHA DE TRIGO COM FERMENTO": ["FARINHA DE TRIGO COM FERMENTO", "Alimentos"],
  "FARINHA LACTA": ["FARINHA LÁCTEA", "Alimentos"],
  "FARINHA LACTEA": ["FARINHA LÁCTEA", "Alimentos"],
  "FECULA": ["FÉCULA DE MANDIOCA", "Alimentos"],
  "FECULA DE BEIJU": ["FÉCULA DE BEIJU", "Alimentos"],
  "FECULA DE MANDIOCA": ["FÉCULA DE MANDIOCA", "Alimentos"],
  "FECULA DE TAPIOCA": ["FÉCULA DE TAPIOCA", "Alimentos"],
  "FEIJAO BRANCO": ["FEIJÃO BRANCO", "Alimentos"],
  "FEIJAO CARIOCA": ["FEIJÃO CARIOCA", "Alimentos"],
  "FEIJAO PRETO": ["FEIJÃO PRETO", "Alimentos"],
  "FERMENTO": ["FERMENTO", "Alimentos"],
  "FIO DE NAYLON": ["FIO DE NYLON", "Atividades/Convivência"],
  "FIO DE SILICONE": ["FIO DE SILICONE", "Atividades/Convivência"],
  "FIO ENCERADO": ["FIO ENCERADO", "Atividades/Convivência"],
  "FITA ADESIVA": ["FITA ADESIVA TRANSPARENTE", "Material de Expediente"],
  "FITA ADESIVA TRANSPARENTE": ["FITA ADESIVA TRANSPARENTE", "Material de Expediente"],
  "FITA CETIN VERDE": ["FITA CETIM VERDE", "Atividades/Convivência"],
  "FITA CREPE": ["FITA CREPE", "Material de Expediente"],
  "FITA DE CETIM": ["FITA CETIM", "Atividades/Convivência"],
  "FITA DECORATIVA": ["FITA DECORATIVA", "Atividades/Convivência"],
  "FITA DECORATIVA CORE VARIADA": ["FITA DECORATIVA CORES VARIADAS", "Atividades/Convivência"],
  "FITA DUPLA FACE": ["FITA DUPLA FACE", "Material de Expediente"],
  "FITA DUREX": ["FITA DUREX", "Material de Expediente"],
  "FITA DUREX GRANDE": ["FITA DUREX", "Material de Expediente"],
  "FITA GOMADA": ["FITA GOMADA", "Material de Expediente"],
  "FITA GOMADA GROSSA": ["FITA GOMADA GROSSA", "Material de Expediente"],
  "FITA GOMADA TRANSPARETE ( URGENTE )": ["FITA GOMADA", "Material de Expediente"],
  "FITA GOMADA/ADESIVA": ["FITA GOMADA", "Material de Expediente"],
  "FITA TRANSPARENTE (GROSSA)": ["FITA ADESIVA TRANSPARENTE", "Material de Expediente"],
  "FITA TRANSPARENTE FINA": ["FITA ADESIVA TRANSPARENTE", "Material de Expediente"],
  "FITILHO BARBANTE DE PLASTICO": ["FITILHO", "Atividades/Convivência"],
  "FITILHO COR LARANJA": ["FITILHO LARANJA", "Atividades/Convivência"],
  "FLANELA": ["FLANELA", "Material de Limpeza"],
  "FLIP-CHART": ["FLIP-CHART", "Material de Expediente"],
  "FLOCAO": ["FLOCÃO DE MILHO", "Alimentos"],
  "FLOCAO DE ARROZ": ["FLOCÃO DE ARROZ", "Alimentos"],
  "FLOCAO DE MILHO": ["FLOCÃO DE MILHO", "Alimentos"],
  "FLOCO DE MILHO": ["FLOCÃO DE MILHO", "Alimentos"],
  "FOLHA DE ISOPOR": ["PLACA DE ISOPOR", "Atividades/Convivência"],
  "FOLHA ISOPOR": ["PLACA DE ISOPOR", "Atividades/Convivência"],
  "FOSFORO": ["FÓSFORO", "Material de Expediente"],
  "FRALDA DESCARTAVEL": ["FRALDA DESCARTÁVEL", "Material Descartável"],
  "FRALDA DESCARTAVEL INFANTIL M": ["FRALDA DESCARTÁVEL INFANTIL M", "Material Descartável"],
  "FRALDA DESCARTAVEL PARA ADULTO G": ["FRALDA DESCARTÁVEL ADULTO G", "Material Descartável"],
  "FRALDA DESCARTAVEL PCF": ["FRALDA DESCARTÁVEL", "Material Descartável"],
  "FRALDA DESCARTAVEL TAMANHO (P.M.G)": ["FRALDA DESCARTÁVEL", "Material Descartável"],
  "FRALDA INFANTIL": ["FRALDA DESCARTÁVEL INFANTIL", "Material Descartável"],
  "FRALDA PARA CRIANCA": ["FRALDA DESCARTÁVEL INFANTIL", "Material Descartável"],
  "FRALDAS": ["FRALDA DESCARTÁVEL", "Material Descartável"],
  "FRANELA": ["FLANELA", "Material de Limpeza"],
  "FUBA": ["FUBÁ", "Alimentos"],
  "FUBA DE ARROZ": ["FUBÁ DE ARROZ", "Alimentos"],
  "FUBA DE MILHO": ["FUBÁ DE MILHO", "Alimentos"],
  "FURADO GRANDE OU PEQUENO": ["PERFURADOR", "Material de Expediente"],
  "GAMPEADOR": ["GRAMPEADOR", "Material de Expediente"],
  "GARFINHOS DESCARTAVEIS": ["GARFO DESCARTÁVEL", "Material Descartável"],
  "GARFO DESCARTAVEL": ["GARFO DESCARTÁVEL", "Material Descartável"],
  "GARRAFA TERMICA CAFE": ["GARRAFA TÉRMICA DE CAFÉ", "Alimentos"],
  "GARRAFA TERMICA DE CAFE": ["GARRAFA TÉRMICA DE CAFÉ", "Alimentos"],
  "GIRATORIO FIT MOP": ["MOP GIRATÓRIO", "Material de Limpeza"],
  "GIZ DE CERA": ["GIZ DE CERA", "Atividades/Convivência"],
  "GRAFITE": ["GRAFITE", "Material de Expediente"],
  "GRAMPEADOR": ["GRAMPEADOR", "Material de Expediente"],
  "GRAMPEADOR GRANDE": ["GRAMPEADOR GRANDE", "Material de Expediente"],
  "GRAMPEADOR MEDIO": ["GRAMPEADOR MÉDIO", "Material de Expediente"],
  "GRAMPEADOR PEQUENO": ["GRAMPEADOR PEQUENO", "Material de Expediente"],
  "GRAMPEADORES": ["GRAMPEADOR", "Material de Expediente"],
  "GRAMPEADORES PEQUENO E MEDIO": ["GRAMPEADOR", "Material de Expediente"],
  "GRAMPO": ["GRAMPO PARA GRAMPEADOR", "Material de Expediente"],
  "GRAMPO MEDIO": ["GRAMPO PARA GRAMPEADOR", "Material de Expediente"],
  "GRAMPO PARA GRAMPEADOR": ["GRAMPO PARA GRAMPEADOR", "Material de Expediente"],
  "GRAMPO PARA GRAMPEDOR 26/6": ["GRAMPO PARA GRAMPEADOR 26/6", "Material de Expediente"],
  "GRAMPO PLASTICO": ["GRAMPO PLÁSTICO", "Material de Expediente"],
  "GRAMPO PRA GRAMPEADOR N24": ["GRAMPO PARA GRAMPEADOR Nº 24", "Material de Expediente"],
  "GRAMPOS": ["GRAMPO PARA GRAMPEADOR", "Material de Expediente"],
  "GRAMPOS PARA GRAMPEADOR": ["GRAMPO PARA GRAMPEADOR", "Material de Expediente"],
  "GRAMPOS PEQUENO": ["GRAMPO PARA GRAMPEADOR", "Material de Expediente"],
  "GRAPEADOR": ["GRAMPEADOR", "Material de Expediente"],
  "GUARADANAPOS DE PAPEL": ["GUARDANAPO", "Material Descartável"],
  "GUARDANAPO": ["GUARDANAPO", "Material Descartável"],
  "GUARDANAPO OU PAPEL TOALHA": ["GUARDANAPO / PAPEL TOALHA", "Material Descartável"],
  "GUARDANAPOS": ["GUARDANAPO", "Material Descartável"],
  "HIDROCOR": ["CANETINHA HIDROCOR", "Atividades/Convivência"],
  "INSETICIDA": ["INSETICIDA", "Material de Limpeza"],
  "INSETICIDA AEROSOL": ["INSETICIDA", "Material de Limpeza"],
  "ISOPOR": ["PLACA DE ISOPOR", "Atividades/Convivência"],
  "ISQUEIRO": ["ISQUEIRO", "Material de Expediente"],
  "JOGOS EDUCATIVOS": ["JOGO EDUCATIVO", "Atividades/Convivência"],
  "KBOLINHAS CRAVO ANTI STRESS": ["BOLINHA ANTI-STRESS", "Atividades/Convivência"],
  "LA CORE SORTIDA": ["LÃ CORES VARIADAS", "Atividades/Convivência"],
  "LA DE ACO": ["PALHA DE AÇO", "Material de Limpeza"],
  "LANTEJOULA COLORIDA": ["LANTEJOULA", "Atividades/Convivência"],
  "LANTEJOULAS COLORIDAS": ["LANTEJOULA", "Atividades/Convivência"],
  "LAPIS": ["LÁPIS GRAFITE", "Material de Expediente"],
  "LAPIS COMUM": ["LÁPIS GRAFITE", "Material de Expediente"],
  "LAPIS DE CERA": ["GIZ DE CERA", "Atividades/Convivência"],
  "LAPIS DE COR": ["LÁPIS DE COR", "Atividades/Convivência"],
  "LAPIS DE ESCREVER": ["LÁPIS GRAFITE", "Material de Expediente"],
  "LAPIS ESCOLAR PRETO": ["LÁPIS GRAFITE", "Material de Expediente"],
  "LAPIS GRAFITE": ["LÁPIS GRAFITE", "Material de Expediente"],
  "LAPIS PRETO SEXTAVADO N 2": ["LÁPIS GRAFITE Nº 2", "Material de Expediente"],
  "LAPIZ PARA COLORIR": ["LÁPIS DE COR", "Atividades/Convivência"],
  "LAVA LOUCAS 500ML": ["DETERGENTE LAVA-LOUÇA", "Material de Limpeza"],
  "LEITE": ["LEITE", "Alimentos"],
  "LEITE CONDENSADO": ["LEITE CONDENSADO", "Alimentos"],
  "LEITE EM PO": ["LEITE EM PÓ", "Alimentos"],
  "LEITE EM PO INTEGRAL": ["LEITE EM PÓ INTEGRAL", "Alimentos"],
  "LEITE LIQUIDO": ["LEITE LÍQUIDO", "Alimentos"],
  "LEITE LIQUIDO INTEGRAL": ["LEITE LÍQUIDO INTEGRAL", "Alimentos"],
  "LEITELIQUIDO": ["LEITE LÍQUIDO", "Alimentos"],
  "LIGA": ["LIGA ELÁSTICA", "Material de Expediente"],
  "LIMPA ALUMINIO": ["LIMPA-ALUMÍNIO", "Material de Limpeza"],
  "LIMPA-ALUMINIO": ["LIMPA-ALUMÍNIO", "Material de Limpeza"],
  "LIMPA-VIDRO": ["LIMPA-VIDRO", "Material de Limpeza"],
  "LIMPADOR MULTIUSO": ["LIMPADOR MULTIUSO", "Material de Limpeza"],
  "LIMPADOR MULTIUSO VEJA": ["LIMPADOR MULTIUSO", "Material de Limpeza"],
  "LINHA DE COSTURA CORE VARIADA": ["LINHA DE COSTURA CORES VARIADAS", "Atividades/Convivência"],
  "LINHA DE CROCHE CORE VARIADA": ["LINHA DE CROCHÊ CORES VARIADAS", "Atividades/Convivência"],
  "LITRO DE OLEO": ["ÓLEO DE SOJA", "Alimentos"],
  "LIVRO ATA": ["LIVRO DE ATA", "Material de Expediente"],
  "LIVRO ATA( GRANDE)": ["LIVRO DE ATA GROSSO", "Material de Expediente"],
  "LIVRO DE ATA": ["LIVRO DE ATA", "Material de Expediente"],
  "LIXEIRA": ["CESTO DE LIXO", "Material de Limpeza"],
  "LIXEIRA C/ TAMPA E PEDAL": ["CESTO DE LIXO COM PEDAL", "Material de Limpeza"],
  "LIXEIRA MEDIA": ["CESTO DE LIXO", "Material de Limpeza"],
  "LIXEIRA OU (CESTO DE LIXO)": ["CESTO DE LIXO", "Material de Limpeza"],
  "LUBRIFICANTE PARA MOVEL": ["LUBRIFICANTE", "Material de Limpeza"],
  "LUSTRA MOVEIS": ["LUSTRA-MÓVEIS", "Material de Limpeza"],
  "LUSTRA MOVEL": ["LUSTRA-MÓVEIS", "Material de Limpeza"],
  "LUVA DE BORRACHA AMARELA": ["LUVA DE BORRACHA", "Material de Limpeza"],
  "LUVA DE CIRURGICA": ["LUVA DESCARTÁVEL", "Material Descartável"],
  "LUVA DE LATEX": ["LUVA DE LÁTEX", "Material de Limpeza"],
  "LUVA DE LATEX MULTIUSO": ["LUVA DE LÁTEX", "Material de Limpeza"],
  "LUVA DE LIMPEZA": ["LUVA DE BORRACHA", "Material de Limpeza"],
  "LUVA DESCARTAVEIS": ["LUVA DESCARTÁVEL", "Material Descartável"],
  "LUVA DESCARTAVEL": ["LUVA DESCARTÁVEL", "Material Descartável"],
  "LUVA DESCATAVEL": ["LUVA DESCARTÁVEL", "Material Descartável"],
  "LUVA DO CANO LONGO": ["LUVA DE BORRACHA CANO LONGO", "Material de Limpeza"],
  "LUVA LATEX": ["LUVA DE LÁTEX", "Material de Limpeza"],
  "LUVA MULTIUSO": ["LUVA DE BORRACHA", "Material de Limpeza"],
  "LUVA PARA LIMPEZA": ["LUVA DE BORRACHA", "Material de Limpeza"],
  "LUVA PVC TAM( P)": ["LUVA PVC TAMANHO P", "Material de Limpeza"],
  "LUVA TAMANHO G": ["LUVA DE BORRACHA TAMANHO G", "Material de Limpeza"],
  "LUVA TAMANHO M": ["LUVA DE BORRACHA TAMANHO M", "Material de Limpeza"],
  "LUVAS": ["LUVA DESCARTÁVEL", "Material Descartável"],
  "LUVAS DE CIRURGICAS": ["LUVA DESCARTÁVEL", "Material Descartável"],
  "LUVAS DE LIMPEZA": ["LUVA DE BORRACHA", "Material de Limpeza"],
  "LUVAS DESCARTAVEIS": ["LUVA DESCARTÁVEL", "Material Descartável"],
  "LUVAS PARA LIMPEZA": ["LUVA DE BORRACHA", "Material de Limpeza"],
  "MACARRAO": ["MACARRÃO", "Alimentos"],
  "MACARRAO (SCFV DE ATE 6ANOS)": ["MACARRÃO", "Alimentos"],
  "MACARRAO PARA ESPAGUETE": ["MACARRÃO ESPAGUETE", "Alimentos"],
  "MAISENA": ["AMIDO DE MILHO", "Alimentos"],
  "MAIZENA": ["AMIDO DE MILHO", "Alimentos"],
  "MANTEIGA": ["MANTEIGA", "Alimentos"],
  "MARCA TEXTO": ["MARCA-TEXTO", "Material de Expediente"],
  "MARCA TEXTO CORES VARIAVEIS": ["MARCA-TEXTO CORES VARIADAS", "Material de Expediente"],
  "MARCA-TEXTO": ["MARCA-TEXTO", "Material de Expediente"],
  "MARCA-TEXTOS": ["MARCA-TEXTO", "Material de Expediente"],
  "MARCADOR DE TEXTO": ["MARCA-TEXTO", "Material de Expediente"],
  "MARCADOR DE TEXTO VARIADO": ["MARCA-TEXTO CORES VARIADAS", "Material de Expediente"],
  "MARCADOR PARA QUADRO BRANCO": ["PINCEL PARA QUADRO BRANCO", "Material de Expediente"],
  "MARCADOR PERMANENTE": ["MARCADOR PERMANENTE", "Material de Expediente"],
  "MARCADOR PERMANENTE AZUL": ["MARCADOR PERMANENTE AZUL", "Material de Expediente"],
  "MARCADOR PERMANENTE AZUL, PRETO": ["MARCADOR PERMANENTE AZUL / MARCADOR PERMANENTE PRETO", "Material de Expediente"],
  "MARCADOR PERMANENTE PRETO": ["MARCADOR PERMANENTE PRETO", "Material de Expediente"],
  "MARCADOR PERMANENTE PRETO E AZUL": ["MARCADOR PERMANENTE AZUL / MARCADOR PERMANENTE PRETO", "Material de Expediente"],
  "MARCADOR PERMANENTE PRETO, VERMELHO": ["MARCADOR PERMANENTE PRETO / MARCADOR PERMANENTE VERMELHO", "Material de Expediente"],
  "MARCADOR PERMANENTE VERMELHO": ["MARCADOR PERMANENTE VERMELHO", "Material de Expediente"],
  "MARCADORES DE TEXTO": ["MARCA-TEXTO", "Material de Expediente"],
  "MARGARINA": ["MARGARINA", "Alimentos"],
  "MARGARINA SEM SAL": ["MARGARINA SEM SAL", "Alimentos"],
  "MARGARINA VEGETAL COM SAL": ["MARGARINA COM SAL", "Alimentos"],
  "MASCARA": ["MÁSCARA DESCARTÁVEL", "Material de Higiene Pessoal"],
  "MASCARA DESCARTAVEIS": ["MÁSCARA DESCARTÁVEL", "Material Descartável"],
  "MASCARA DESCARTAVEL": ["MÁSCARA DESCARTÁVEL", "Material Descartável"],
  "MASCARAS": ["MÁSCARA DESCARTÁVEL", "Material de Higiene Pessoal"],
  "MASCARAS DESCARTAVEIS": ["MÁSCARA DESCARTÁVEL", "Material Descartável"],
  "MASSA DE BOLO PRONTA": ["MASSA PRONTA PARA BOLO", "Alimentos"],
  "MASSA DE BOLO PRONTO": ["MASSA PRONTA PARA BOLO", "Alimentos"],
  "MASSA DE CUSCUZ": ["MASSA DE CUSCUZ", "Alimentos"],
  "MASSA DE MODELAR": ["MASSA DE MODELAR", "Atividades/Convivência"],
  "MASSA DE TAPIOCA": ["MASSA DE TAPIOCA", "Alimentos"],
  "MASSA DE TAPIOCA PARA MINGAU": ["MASSA DE TAPIOCA PARA MINGAU", "Alimentos"],
  "MASSA DE TRIGO SEM FERMENTO": ["FARINHA DE TRIGO SEM FERMENTO", "Alimentos"],
  "MASSA PARA BOLO": ["MASSA PRONTA PARA BOLO", "Alimentos"],
  "MASSA PARA CUSCUZ": ["MASSA DE CUSCUZ", "Alimentos"],
  "MASSA PARA MINGAU DE TAPIOCA": ["MASSA DE TAPIOCA PARA MINGAU", "Alimentos"],
  "MASSA PARA MINGUAU DE TAPIOCA": ["MASSA DE TAPIOCA PARA MINGAU", "Alimentos"],
  "MASSA PARA MODELAR": ["MASSA DE MODELAR", "Atividades/Convivência"],
  "MASSA PRA MINGAU": ["MASSA PARA MINGAU", "Alimentos"],
  "MASSA PRONTA PARA BOLO": ["MASSA PRONTA PARA BOLO", "Alimentos"],
  "MICANGA GRANDE CORE VARIADA": ["MIÇANGAS CORES VARIADAS", "Atividades/Convivência"],
  "MILHO BRANCO PARA MINGAU": ["MILHO BRANCO PARA MINGAU", "Alimentos"],
  "MILHO DE MIGUAL": ["MILHO PARA MINGAU", "Alimentos"],
  "MILHO DE MINGAU": ["MILHO PARA MINGAU", "Alimentos"],
  "MILHO DE PIPOCA": ["MILHO PARA PIPOCA", "Alimentos"],
  "MILHO EM CONSERVA": ["MILHO VERDE EM CONSERVA", "Alimentos"],
  "MILHO P/MINGAU": ["MILHO PARA MINGAU", "Alimentos"],
  "MILHO P/PIPOCA": ["MILHO PARA PIPOCA", "Alimentos"],
  "MILHO PARA MINGAU": ["MILHO PARA MINGAU", "Alimentos"],
  "MILHO PARA PIPOCA": ["MILHO PARA PIPOCA", "Alimentos"],
  "MILHO VERDE EM LATA": ["MILHO VERDE EM CONSERVA", "Alimentos"],
  "MINGAU DE MILHO": ["MINGAU DE MILHO", "Alimentos"],
  "MINGAU DE TAPIOCA": ["MINGAU DE TAPIOCA", "Alimentos"],
  "MINGAU DE TAPIOCA C/ COCO": ["MINGAU DE TAPIOCA COM COCO", "Alimentos"],
  "MISTURA PARA BOLO": ["MASSA PRONTA PARA BOLO", "Alimentos"],
  "MOLHO DE TOMATE": ["MOLHO DE TOMATE", "Alimentos"],
  "MUCILON": ["MUCILON", "Alimentos"],
  "MULTIUSO": ["LIMPADOR MULTIUSO", "Material de Limpeza"],
  "MUSSILON": ["MUCILON", "Alimentos"],
  "NESCAU": ["ACHOCOLATADO EM PÓ", "Alimentos"],
  "OLEO": ["ÓLEO DE SOJA", "Alimentos"],
  "OLEO DE SOJA": ["ÓLEO DE SOJA", "Alimentos"],
  "ORGANIZADOR DE DOCUMENTO": ["ORGANIZADOR DE DOCUMENTOS", "Material de Expediente"],
  "ORGANIZADOR DE FOLHA": ["ORGANIZADOR DE DOCUMENTOS", "Material de Expediente"],
  "ORGANIZADOR DE FOLHAS": ["ORGANIZADOR DE DOCUMENTOS", "Material de Expediente"],
  "ORGANIZADOR DE MESA (PORTA CANETA)": ["PORTA-CANETAS", "Material de Expediente"],
  "ORGANIZADOR DE MESA( PORTA OBJETO)": ["ORGANIZADOR DE MESA", "Material de Expediente"],
  "OVO": ["OVO", "Alimentos"],
  "OVOS": ["OVO", "Alimentos"],
  "PA DE LIXO": ["PÁ DE LIXO", "Material de Limpeza"],
  "PACOTE DE ACUCAR": ["AÇÚCAR", "Alimentos"],
  "PACOTE DE BALAO DE AR": ["BALÃO CORES VARIADAS", "Atividades/Convivência"],
  "PACOTE DE FOSFORO": ["FÓSFORO", "Material de Expediente"],
  "PACOTE DE FOSFOROS": ["FÓSFORO", "Material de Expediente"],
  "PACOTE DE PAPEL HIGIENICO": ["PAPEL HIGIÊNICO", "Material de Higiene Pessoal"],
  "PAITE (LANTEJOULA)": ["LANTEJOULA", "Atividades/Convivência"],
  "PALHA DE ACO": ["PALHA DE AÇO", "Material de Limpeza"],
  "PALHA DE ACO BOMBRIL": ["PALHA DE AÇO", "Material de Limpeza"],
  "PALITO DE CHURRASCO": ["PALITO DE CHURRASCO", "Material Descartável"],
  "PALITO DE PICOLE": ["PALITO DE PICOLE", "Material Descartável"],
  "PANELA DE PASSAR CAFE": ["COADOR DE CAFÉ", "Alimentos"],
  "PANO CHAO": ["PANO DE CHÃO", "Material de Limpeza"],
  "PANO DE CHAO": ["PANO DE CHÃO", "Material de Limpeza"],
  "PANO DE LIMPEZA PERFEX": ["PANO MULTIUSO", "Material de Limpeza"],
  "PANO DE PIA": ["PANO DE PIA", "Material de Limpeza"],
  "PANO DE PIA/FLANELA": ["FLANELA", "Material de Limpeza"],
  "PANO DE PRATO": ["PANO DE PRATO", "Material Descartável"],
  "PANO MULTIUSO": ["PANO MULTIUSO", "Material de Limpeza"],
  "PANO MULTIUSO PARA PIA": ["PANO MULTIUSO", "Material de Limpeza"],
  "PANOS LIMPOS": ["PANO MULTIUSO", "Material de Limpeza"],
  "PAO DE FORMA": ["PÃO DE FORMA", "Alimentos"],
  "PAPEL 40KG PARA CAVALETE": ["PAPEL 40KG PARA CAVALETE", "Material de Expediente"],
  "PAPEL A4": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "PAPEL A4 ( COR VERDE/AMARELA/ROSA/AZUL)": ["RESMA DE PAPEL A4 COLORIDO", "Material de Expediente"],
  "PAPEL A4 VERGE": ["PAPEL VERGÊ A4", "Material de Expediente"],
  "PAPEL A4( CADASTRO UNICO": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "PAPEL A4( CADASTRO UNICO E CRAS)( EXTREMAMENTE NECESSARIO)": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "PAPEL A4( PROGRAMA PRIMEIRA INFANCIA NO SUAS) (": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "PAPEL A4( SERVICO DE CONVIVENCIA E FORTALECIMENTO DE VINCULOS)": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "PAPEL ADESIVO DE PAPEL": ["PAPEL ADESIVO", "Material de Expediente"],
  "PAPEL ALMACO": ["PAPEL ALMAÇO", "Material de Expediente"],
  "PAPEL ALUMINIO": ["PAPEL ALUMÍNIO", "Material de Expediente"],
  "PAPEL CAMURCA (DIVERSAS CORES)": ["PAPEL CAMURÇA CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL CAMURCA AMARELO": ["PAPEL CAMURÇA AMARELO", "Atividades/Convivência"],
  "PAPEL CAMURCA AZUL AMARELO": ["PAPEL CAMURÇA CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL CAMURCA AZUL PRETO": ["PAPEL CAMURÇA CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL CAMURCA COR LARANJA": ["PAPEL CAMURÇA LARANJA", "Atividades/Convivência"],
  "PAPEL CARTAO": ["PAPEL CARTÃO", "Material de Expediente"],
  "PAPEL CARTAO (DIVERSAS CORES)": ["PAPEL CARTÃO CORES VARIADAS", "Material de Expediente"],
  "PAPEL CARTAO CORE VARIADA": ["PAPEL CARTÃO CORES VARIADAS", "Material de Expediente"],
  "PAPEL CARTAO CORES VARIADAS": ["PAPEL CARTÃO CORES VARIADAS", "Material de Expediente"],
  "PAPEL CARTAO VARIADO": ["PAPEL CARTÃO CORES VARIADAS", "Material de Expediente"],
  "PAPEL CERTIFICADO": ["PAPEL CERTIFICADO", "Material de Expediente"],
  "PAPEL CHAMEX": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "PAPEL CHAMEX A4": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "PAPEL COLOR 7": ["PAPEL COLORIDO", "Material de Expediente"],
  "PAPEL COLORSET CORE VARIADA": ["PAPEL COLORSET CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL COLORSET CORES VARIADAS": ["PAPEL COLORSET CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL CREPOM CORE VARIADO": ["PAPEL CREPOM CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL CREPOM VARIADO": ["PAPEL CREPOM CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL CREPOM VERMELHO, BRANCO": ["PAPEL CREPOM CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL CREPON CORE VARIADA": ["PAPEL CREPOM CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL CRIATIVO": ["PAPEL CRIATIVO", "Atividades/Convivência"],
  "PAPEL CRIATIVO CORE VARIADA": ["PAPEL CRIATIVO", "Atividades/Convivência"],
  "PAPEL DE SEDA": ["PAPEL SEDA", "Material de Expediente"],
  "PAPEL DE SEDA / VERDE- LARANJA": ["PAPEL SEDA", "Material de Expediente"],
  "PAPEL FILME": ["PAPEL FILME", "Material de Expediente"],
  "PAPEL FOTO (OFICINA PCF)": ["PAPEL FOTOGRÁFICO", "Atividades/Convivência"],
  "PAPEL FOTOGRAFICO": ["PAPEL FOTOGRÁFICO", "Atividades/Convivência"],
  "PAPEL GREPOM PRETO, AZUL": ["PAPEL CREPOM CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL GREPOM PRETO, VERDE": ["PAPEL CREPOM CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL GUACHE": ["PAPEL PARA PINTURA", "Atividades/Convivência"],
  "PAPEL HIGIENICO": ["PAPEL HIGIÊNICO", "Material de Higiene Pessoal"],
  "PAPEL HIGIENIICO": ["PAPEL HIGIÊNICO", "Material de Higiene Pessoal"],
  "PAPEL LAMINADO                                  UND": ["PAPEL LAMINADO", "Atividades/Convivência"],
  "PAPEL LAMINADO DOURADO PRATA VERDE": ["PAPEL LAMINADO CORES VARIADAS", "Atividades/Convivência"],
  "PAPEL LAMINADO VERMELHO": ["PAPEL LAMINADO VERMELHO", "Atividades/Convivência"],
  "PAPEL PARDO": ["PAPEL PARDO", "Material de Expediente"],
  "PAPEL TOALHA": ["PAPEL TOALHA", "Material de Higiene Pessoal"],
  "PAPEL TOALHA EM FOLHA": ["PAPEL TOALHA", "Material de Higiene Pessoal"],
  "PAPEL TOLHA": ["PAPEL TOALHA", "Material de Higiene Pessoal"],
  "PAPEL VERGE": ["PAPEL VERGÊ", "Material de Expediente"],
  "PAPEL VG": ["PAPEL VERGÊ", "Material de Expediente"],
  "PASTA 3 CM": ["PASTA AZ 3CM", "Material de Expediente"],
  "PASTA 5 CM": ["PASTA AZ 5CM", "Material de Expediente"],
  "PASTA A - Z": ["PASTA AZ", "Material de Expediente"],
  "PASTA A -Z": ["PASTA AZ", "Material de Expediente"],
  "PASTA A / Z": ["PASTA AZ", "Material de Expediente"],
  "PASTA A-Z": ["PASTA AZ", "Material de Expediente"],
  "PASTA A4": ["PASTA A4", "Material de Expediente"],
  "PASTA ABA COM ELASTICO A4": ["PASTA COM ELÁSTICO A4", "Material de Expediente"],
  "PASTA ABA ELASTICO": ["PASTA COM ELÁSTICO", "Material de Expediente"],
  "PASTA ARQUIVO": ["PASTA AZ", "Material de Expediente"],
  "PASTA ARQUIVO A-Z": ["PASTA AZ", "Material de Expediente"],
  "PASTA AZ": ["PASTA AZ", "Material de Expediente"],
  "PASTA C/ELASTICO": ["PASTA COM ELÁSTICO", "Material de Expediente"],
  "PASTA CANELETA LARGA 5CM": ["PASTA AZ 5CM", "Material de Expediente"],
  "PASTA CATALAGO": ["PASTA CATÁLOGO", "Material de Expediente"],
  "PASTA CATALOGO": ["PASTA CATÁLOGO", "Material de Expediente"],
  "PASTA CATALOGO PVC": ["PASTA CATÁLOGO", "Material de Expediente"],
  "PASTA COM ABA ELASTICO": ["PASTA COM ELÁSTICO", "Material de Expediente"],
  "PASTA COM ELASTICO": ["PASTA COM ELÁSTICO", "Material de Expediente"],
  "PASTA COM GRAMPO TRILHO": ["PASTA COM GRAMPO TRILHO", "Material de Expediente"],
  "PASTA COMUNS C/ELASTICO": ["PASTA COM ELÁSTICO", "Material de Expediente"],
  "PASTA DE DOCUMENTOS": ["PASTA DE DOCUMENTOS", "Material de Expediente"],
  "PASTA DE PLASTICO (PEQUENA E GRANDE)": ["PASTA PLÁSTICA", "Material de Expediente"],
  "PASTA DE PLASTICO GRANDE": ["PASTA PLÁSTICA GRANDE", "Material de Expediente"],
  "PASTA DE PLASTICO PEQUENA": ["PASTA PLÁSTICA PEQUENA", "Material de Expediente"],
  "PASTA ESCARCELA": ["PASTA ESCARCELA", "Material de Expediente"],
  "PASTA ESCARCELA GRANDE": ["PASTA ESCARCELA GRANDE", "Material de Expediente"],
  "PASTA ESCARCELA PEQUENA": ["PASTA ESCARCELA PEQUENA", "Material de Expediente"],
  "PASTA FINA": ["PASTA ESCARCELA FINA", "Material de Expediente"],
  "PASTA FINA E GROSSA": ["PASTA ESCARCELA", "Material de Expediente"],
  "PASTA GRAMPO TRILHO": ["PASTA COM GRAMPO TRILHO", "Material de Expediente"],
  "PASTA GROSSA": ["PASTA ESCARCELA GROSSA", "Material de Expediente"],
  "PASTA L A4": ["PASTA L A4", "Material de Expediente"],
  "PASTA P/ARQUIVO MORTO": ["PASTA PARA ARQUIVO MORTO", "Material de Expediente"],
  "PASTA PARA ARQUIVO": ["PASTA AZ", "Material de Expediente"],
  "PASTA PLASTICA": ["PASTA PLÁSTICA", "Material de Expediente"],
  "PASTA PLASTICA C/ ELASTICO": ["PASTA COM ELÁSTICO", "Material de Expediente"],
  "PASTA PLASTICA C/ELASTICO 245X55X335MM": ["PASTA COM ELÁSTICO A4", "Material de Expediente"],
  "PASTA PLASTICA C/ELASTICO A4 ( 4CM)": ["PASTA COM ELÁSTICO A4", "Material de Expediente"],
  "PASTA PLASTICA GRANDE": ["PASTA PLÁSTICA GRANDE", "Material de Expediente"],
  "PASTA PLASTICA SAFONADA": ["PASTA SANFONADA", "Material de Expediente"],
  "PASTA POLIBRA": ["PASTA PLÁSTICA", "Material de Expediente"],
  "PASTA POLIONDA": ["PASTA POLIONDA", "Material de Expediente"],
  "PASTA POLIONDA C/ELASTICO": ["PASTA POLIONDA COM ELÁSTICO", "Material de Expediente"],
  "PASTA POLIONDA COM ELASTICO": ["PASTA POLIONDA COM ELÁSTICO", "Material de Expediente"],
  "PASTA REGISTRADORA A/Z OFICIO": ["PASTA AZ OFÍCIO", "Material de Expediente"],
  "PASTA SANFONADA": ["PASTA SANFONADA", "Material de Expediente"],
  "PASTA SANFONADA A4": ["PASTA SANFONADA A4", "Material de Expediente"],
  "PASTA SUSPENSA": ["PASTA SUSPENSA", "Material de Expediente"],
  "PASTA ZIPADA": ["PASTA COM ELÁSTICO", "Material de Expediente"],
  "PASTAS": ["PASTA", "Material de Expediente"],
  "PASTAS A-Z": ["PASTA AZ", "Material de Expediente"],
  "PASTAS COMUNS C/ELASTICO": ["PASTA COM ELÁSTICO", "Material de Expediente"],
  "PASTAS ESCARCELA": ["PASTA ESCARCELA", "Material de Expediente"],
  "PASTAS PLASTICAS": ["PASTA PLÁSTICA", "Material de Expediente"],
  "PEDRA P/VASO": ["PEDRA SANITÁRIA", "Material de Limpeza"],
  "PEDRA SANITARIA": ["PEDRA SANITÁRIA", "Material de Limpeza"],
  "PEFURADOR PEQUENO": ["PERFURADOR PEQUENO", "Material de Expediente"],
  "PEN DRIVE": ["PEN DRIVE", "Material de Expediente"],
  "PERCEVEJO": ["PERCEVEJO PARA MURAL", "Material de Expediente"],
  "PERCEVEJOS": ["PERCEVEJO PARA MURAL", "Material de Expediente"],
  "PERFEX": ["PANO MULTIUSO", "Material de Limpeza"],
  "PERFURADO": ["PERFURADOR", "Material de Expediente"],
  "PERFURADOR": ["PERFURADOR", "Material de Expediente"],
  "PERFURADOR DE PAPEL": ["PERFURADOR", "Material de Expediente"],
  "PERFURADOR MEDIO": ["PERFURADOR MÉDIO", "Material de Expediente"],
  "PILHA AAA": ["PILHA AAA", "Material de Expediente"],
  "PILHA PALITO (AAA)": ["PILHA AAA", "Material de Expediente"],
  "PILHAS AAA": ["PILHA AAA", "Material de Expediente"],
  "PILOTO PERMANENTE": ["MARCADOR PERMANENTE", "Material de Expediente"],
  "PINCEIS ATOMICOS (AZUL, PRETO, VERMELHO)": ["MARCADOR PERMANENTE", "Material de Expediente"],
  "PINCEL ATOMICO": ["PINCEL ATÔMICO", "Material de Expediente"],
  "PINCEL ATOMICO GROSSO 110": ["PINCEL ATÔMICO GROSSO", "Material de Expediente"],
  "PINCEL ATOMICO PARA QUADRO BRANCO": ["PINCEL PARA QUADRO BRANCO", "Material de Expediente"],
  "PINCEL CANETAO": ["PINCEL ATÔMICO", "Material de Expediente"],
  "PINCEL N 10": ["PINCEL Nº 10", "Material de Expediente"],
  "PINCEL N 20": ["PINCEL Nº 20", "Material de Expediente"],
  "PINCEL N 30": ["PINCEL Nº 30", "Material de Expediente"],
  "PINCEL P/ QUADRO BRANCO": ["PINCEL PARA QUADRO BRANCO", "Material de Expediente"],
  "PINCEL PARA PINTURA EM PAPEL": ["PINCEL PARA PINTURA", "Atividades/Convivência"],
  "PINCEL PARA PINTURA GRANDE": ["PINCEL PARA PINTURA GRANDE", "Atividades/Convivência"],
  "PINCEL PARA PINTURA PEQUENO": ["PINCEL PARA PINTURA PEQUENO", "Atividades/Convivência"],
  "PINCEL PARA QUADRO BRANCO": ["PINCEL PARA QUADRO BRANCO", "Material de Expediente"],
  "PINCEL PEQUENO PERMANENTE": ["PINCEL PARA PINTURA PEQUENO", "Atividades/Convivência"],
  "PINCEL PERMANENTE PRETO": ["MARCADOR PERMANENTE PRETO", "Material de Expediente"],
  "PINCEL QUADRO BRANCO": ["PINCEL PARA QUADRO BRANCO", "Material de Expediente"],
  "PINCEL QUADRO BRANCO AZUL": ["PINCEL PARA QUADRO BRANCO AZUL", "Material de Expediente"],
  "PISTOLA": ["PISTOLA DE COLA QUENTE", "Atividades/Convivência"],
  "PISTOLA COLA QUENTE": ["PISTOLA DE COLA QUENTE", "Atividades/Convivência"],
  "PISTOLA DE COLA QUENTE": ["PISTOLA DE COLA QUENTE", "Atividades/Convivência"],
  "PLACA DE ISOPOR": ["PLACA DE ISOPOR", "Atividades/Convivência"],
  "PLANCHETA": ["PRANCHETA", "Material de Expediente"],
  "PLASTA CATALAGO": ["PASTA CATÁLOGO", "Material de Expediente"],
  "PORT IT": ["POST-IT", "Material de Expediente"],
  "PORTA CANETA": ["PORTA-CANETAS", "Material de Expediente"],
  "PORTA CANETAS": ["PORTA-CANETAS", "Material de Expediente"],
  "PORTA DOCUMENTOS DUPLA": ["PORTA DOCUMENTOS", "Material de Expediente"],
  "PORTA PAPEL TOALHA": ["PORTA PAPEL TOALHA", "Material de Higiene Pessoal"],
  "PORTA SABAO PARA PIA": ["PORTA SABÃO", "Material de Limpeza"],
  "PORTA SABAO/DETERGENTE PARA PIA DE COZINHA": ["PORTA SABÃO", "Material de Limpeza"],
  "PORTA-CANETAS": ["PORTA-CANETAS", "Material de Expediente"],
  "PORTA-LAPIS": ["PORTA-LÁPIS", "Material de Expediente"],
  "PORTIFOLIO": ["PASTA CATÁLOGO", "Material de Expediente"],
  "POST IT": ["POST-IT", "Material de Expediente"],
  "POST IT (BLOCO DE ANOTACOES) GRANDE": ["POST-IT GRANDE", "Material de Expediente"],
  "POST'IT": ["POST-IT", "Material de Expediente"],
  "POST'IT GRANDE": ["POST-IT GRANDE", "Material de Expediente"],
  "POST-IT": ["POST-IT", "Material de Expediente"],
  "POST-IT (BLOCO DE ANOTACOES) GRANDE": ["POST-IT GRANDE", "Material de Expediente"],
  "POSTICHE": ["POST-IT", "Material de Expediente"],
  "POSTIFOLIO": ["PASTA CATÁLOGO", "Material de Expediente"],
  "POSTITE": ["POST-IT", "Material de Expediente"],
  "PRANCETA": ["PRANCHETA", "Material de Expediente"],
  "PRANCHETA": ["PRANCHETA", "Material de Expediente"],
  "PRANCHETA A4": ["PRANCHETA A4", "Material de Expediente"],
  "PRANCHETAS": ["PRANCHETA", "Material de Expediente"],
  "PRATINHO DESCARTAVEIS": ["PRATO DESCARTÁVEL", "Material Descartável"],
  "PRATINHOS DESCARTAVEIS": ["PRATO DESCARTÁVEL", "Material Descartável"],
  "PRATO": ["PRATO DESCARTÁVEL", "Material Descartável"],
  "PRATO DESCARTAVEIS": ["PRATO DESCARTÁVEL", "Material Descartável"],
  "PRATO DESCARTAVEL": ["PRATO DESCARTÁVEL", "Material Descartável"],
  "PRATO PARA BOLO DESCARTAVEL": ["PRATO DESCARTÁVEL PARA BOLO", "Material Descartável"],
  "PRATOS": ["PRATO DESCARTÁVEL", "Material Descartável"],
  "PRATOS DESCARTAVEIS": ["PRATO DESCARTÁVEL", "Material Descartável"],
  "PROTETOR FACIAL": ["PROTETOR FACIAL", "Material de Higiene Pessoal"],
  "QUADRO BRANCO PEQUENO": ["QUADRO BRANCO", "Material de Expediente"],
  "REGUA": ["RÉGUA", "Material de Expediente"],
  "REGUAS": ["RÉGUA", "Material de Expediente"],
  "REQUEIJAO": ["REQUEIJÃO", "Alimentos"],
  "RESMA": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA A4": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA CHAMEX": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA DE CHAMEX": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA DE PAPEL": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA DE PAPEL A4": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA DE PAPEL A4 FORTALECIMENTO DE VINCULO": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA DE PAPEL A4 SERVICO DE CONVIVENCIA": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA PAPEL": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA PAPEL A4": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA PAPEL CHAMEX": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA PAPEL CHAMEX A4": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMA PAPEL CHAMEX A4 /PARA PAAIF/ SCFV/ E PCF": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RESMAS DE PAPEL": ["RESMA DE PAPEL A4", "Material de Expediente"],
  "RODO": ["RODO", "Material de Limpeza"],
  "RODO GRANDE": ["RODO GRANDE", "Material de Limpeza"],
  "ROLO DE BARBANTE": ["BARBANTE", "Atividades/Convivência"],
  "ROLO DE FITA GOMADA": ["FITA GOMADA", "Material de Expediente"],
  "SABAO BARRA": ["SABÃO EM BARRA", "Material de Limpeza"],
  "SABAO EM BARRA": ["SABÃO EM BARRA", "Material de Limpeza"],
  "SABAO EM PEDRA": ["SABÃO EM PEDRA", "Material de Limpeza"],
  "SABAO EM PO": ["SABÃO EM PÓ", "Material de Limpeza"],
  "SABAO EM PO 500G": ["SABÃO EM PÓ", "Material de Limpeza"],
  "SABAO EM PO/BARRA": ["SABÃO EM PÓ", "Material de Limpeza"],
  "SABAO EMBARRA": ["SABÃO EM BARRA", "Material de Limpeza"],
  "SABAO EMPEDRA": ["SABÃO EM PEDRA", "Material de Limpeza"],
  "SABAO LIQUIDO": ["SABÃO LÍQUIDO", "Material de Limpeza"],
  "SABAO LIQUIDO DETERGENTE LAVA-LOUCA": ["DETERGENTE LAVA-LOUÇA", "Material de Limpeza"],
  "SABAO LIQUIDO PARA LAVAR AS MAO": ["SABÃO LÍQUIDO", "Material de Limpeza"],
  "SABONETE BARRA": ["SABONETE EM BARRA", "Material de Higiene Pessoal"],
  "SABONETE EM BARRA": ["SABONETE EM BARRA", "Material de Higiene Pessoal"],
  "SABONETE LAVAR MAO": ["SABONETE LÍQUIDO", "Material de Higiene Pessoal"],
  "SABONETE LAVAR MAOS": ["SABONETE LÍQUIDO", "Material de Higiene Pessoal"],
  "SABONETE LIQUIDO": ["SABONETE LÍQUIDO", "Material de Higiene Pessoal"],
  "SABONETE LIQUIDO PARA MAO": ["SABONETE LÍQUIDO", "Material de Higiene Pessoal"],
  "SABONETE PARA AS MAO": ["SABONETE LÍQUIDO", "Material de Higiene Pessoal"],
  "SABONETE PARA AS MAOS": ["SABONETE LÍQUIDO", "Material de Higiene Pessoal"],
  "SABONETE/SABAO LIQUIDO": ["SABONETE LÍQUIDO", "Material de Higiene Pessoal"],
  "SACO DE LIXO": ["SACO DE LIXO", "Material Descartável"],
  "SACO DE LIXO ( 50K. 30K. )": ["SACO DE LIXO", "Material Descartável"],
  "SACO DE LIXO (15L/50L/100L)": ["SACO DE LIXO", "Material Descartável"],
  "SACO DE LIXO (200) LITRO PARA OS FINAI DE SEMANA": ["SACO DE LIXO 200L", "Material Descartável"],
  "SACO DE LIXO 100": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO 100 L": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO 100 LITROS": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO 100 LT": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO 100 ML": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO 100L": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO 100ML": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO 15 LITRO": ["SACO DE LIXO 15L", "Material Descartável"],
  "SACO DE LIXO 15L": ["SACO DE LIXO 15L", "Material Descartável"],
  "SACO DE LIXO 20 L": ["SACO DE LIXO 20L", "Material Descartável"],
  "SACO DE LIXO 20 LT": ["SACO DE LIXO 20L", "Material Descartável"],
  "SACO DE LIXO 30": ["SACO DE LIXO 30L", "Material Descartável"],
  "SACO DE LIXO 30 L": ["SACO DE LIXO 30L", "Material Descartável"],
  "SACO DE LIXO 30L": ["SACO DE LIXO 30L", "Material Descartável"],
  "SACO DE LIXO 50": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO DE LIXO 50 L": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO DE LIXO 50 LITROS": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO DE LIXO 50 ML": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO DE LIXO 50L": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO DE LIXO 50ML": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO DE LIXO 60 L": ["SACO DE LIXO 60L", "Material Descartável"],
  "SACO DE LIXO DE 100 L": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO DE 100 LITROS": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO DE 15": ["SACO DE LIXO 15L", "Material Descartável"],
  "SACO DE LIXO DE 20LT": ["SACO DE LIXO 20L", "Material Descartável"],
  "SACO DE LIXO DE 30 LITRO": ["SACO DE LIXO 30L", "Material Descartável"],
  "SACO DE LIXO DE 30 LITROS": ["SACO DE LIXO 30L", "Material Descartável"],
  "SACO DE LIXO DE 50 L": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO DE LIXO DE 50 LITRO": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO DE LIXO DE 50 LITROS": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO DE LIXO GRANDE 100L": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO PEQUENO 20L": ["SACO DE LIXO 20L", "Material Descartável"],
  "SACO DE LIXO/ 30/50": ["SACO DE LIXO 30L / SACO DE LIXO 50L", "Material Descartável"],
  "SACO DE LIXO100 LITRO": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO DE LIXO100 LITROS": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO P/ LIXO 100L": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO P/ LIXO 50L": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO P/ LIXO 50L E DE 100L": ["SACO DE LIXO 50L / SACO DE LIXO 100L", "Material Descartável"],
  "SACO P/LIXO 100 L": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO P/LIXO 100L": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO P/LIXO 30 L": ["SACO DE LIXO 30L", "Material Descartável"],
  "SACO P/LIXO 50 L": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO P/LIXO 50L": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO P/LIXO 50L E DE 100L": ["SACO DE LIXO 50L / SACO DE LIXO 100L", "Material Descartável"],
  "SACO PARA LIXO": ["SACO DE LIXO", "Material Descartável"],
  "SACO PARA LIXO 100 L": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO PARA LIXO 100L": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACO PARA LIXO 30 L": ["SACO DE LIXO 30L", "Material Descartável"],
  "SACO PARA LIXO 30 L E DE 50 L 100": ["SACO DE LIXO 30L / 50L / 100L", "Material Descartável"],
  "SACO PARA LIXO 50 L": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO PARA LIXO 50L": ["SACO DE LIXO 50L", "Material Descartável"],
  "SACO PLASTICO A4 DE POLIPROPILENO": ["SACO PLÁSTICO A4", "Material de Expediente"],
  "SACOS DE LIXO 100L": ["SACO DE LIXO 100L", "Material Descartável"],
  "SACOS DE LIXO 30L": ["SACO DE LIXO 30L", "Material Descartável"],
  "SACOS DE LIXO 50L": ["SACO DE LIXO 50L", "Material Descartável"],
  "SAL": ["SAL", "Alimentos"],
  "SALGADINHOS": ["SALGADINHOS", "Alimentos"],
  "SALSICHA": ["SALSICHA EM LATA", "Alimentos"],
  "SARDINHA": ["SARDINHA EM LATA", "Alimentos"],
  "SARDINHA AO MOLHO DE TOMATE": ["SARDINHA AO MOLHO DE TOMATE", "Alimentos"],
  "SARDINHA AO OLEO": ["SARDINHA AO ÓLEO", "Alimentos"],
  "SARDINHA EM LATA": ["SARDINHA EM LATA", "Alimentos"],
  "SARDINHA LATA(SCFV DE ATE 6 ANO": ["SARDINHA EM LATA", "Alimentos"],
  "SPEDRA SANITARIA": ["PEDRA SANITÁRIA", "Material de Limpeza"],
  "SPLAY BOM AR": ["BOM AR", "Material de Limpeza"],
  "SUCO": ["SUCO", "Alimentos"],
  "SUCO CONCENTRADO SABOR UVA NATURAL": ["SUCO DE UVA", "Alimentos"],
  "SUCO DE CAIXA": ["SUCO DE CAIXINHA", "Alimentos"],
  "SUCO DE CAIXINHA": ["SUCO DE CAIXINHA", "Alimentos"],
  "SUCO DE PACOTE": ["SUCO EM PÓ", "Alimentos"],
  "SUCO EM CAIXA INDIVIDUALIZADA": ["SUCO DE CAIXINHA", "Alimentos"],
  "SUCO EM PO": ["SUCO EM PÓ", "Alimentos"],
  "SUCO LIQUIDO": ["SUCO DE CAIXINHA", "Alimentos"],
  "SUPORTE PARA FITA ADESIVA (DUREX DE MESA)": ["SUPORTE PARA FITA ADESIVA", "Material de Expediente"],
  "TAPIOCA": ["TAPIOCA", "Alimentos"],
  "TAPIOCA / FECULA": ["TAPIOCA", "Alimentos"],
  "TAPIOCA GROSSA": ["TAPIOCA GROSSA", "Alimentos"],
  "TATAME COLORIDO": ["TATAME COLORIDO", "Atividades/Convivência"],
  "TECIDO CHITAO": ["TECIDO CHITÃO", "Atividades/Convivência"],
  "TECIDO FELTRO (COLORIDO)": ["FELTRO CORES VARIADAS", "Atividades/Convivência"],
  "TEMPERO SECO": ["TEMPERO SECO EM PÓ", "Alimentos"],
  "TEMPERO SECO EM PO": ["TEMPERO SECO EM PÓ", "Alimentos"],
  "TESOURA": ["TESOURA", "Material de Expediente"],
  "TESOURA DE PICOTE": ["TESOURA DE PICOTE", "Material de Expediente"],
  "TESOURA GRANDE": ["TESOURA GRANDE", "Material de Expediente"],
  "TESOURA PEQUENA (PARA O SCFV)": ["TESOURA PEQUENA", "Material de Expediente"],
  "TESOURAS PEQUENA": ["TESOURA PEQUENA", "Material de Expediente"],
  "TESOURINHA": ["TESOURA PEQUENA", "Material de Expediente"],
  "TESSOURA": ["TESOURA", "Material de Expediente"],
  "TILIBRA - PRENDEDOR PARA PAPEL": ["CLIPS", "Material de Expediente"],
  "TINTA AZUL PARA CARIMBO": ["TINTA PARA CARIMBO AZUL", "Atividades/Convivência"],
  "TINTA DE TECIDO CORE VARIADA": ["TINTA PARA TECIDO CORES VARIADAS", "Atividades/Convivência"],
  "TINTA GUACHE": ["TINTA GUACHE", "Atividades/Convivência"],
  "TINTA P/ CARIMBO (AZUL/PRETA)": ["TINTA PARA CARIMBO", "Atividades/Convivência"],
  "TINTA P/ CARIMBO AZUL": ["TINTA PARA CARIMBO AZUL", "Atividades/Convivência"],
  "TINTA P/ CARIMBO PRETA": ["TINTA PARA CARIMBO PRETA", "Atividades/Convivência"],
  "TINTA PARA ALMOFADA DE CARIMBO": ["TINTA PARA CARIMBO", "Atividades/Convivência"],
  "TINTA PARA CARIMBO": ["TINTA PARA CARIMBO", "Atividades/Convivência"],
  "TINTA PARA CARIMBO AZUL": ["TINTA PARA CARIMBO AZUL", "Atividades/Convivência"],
  "TINTA PARA TECIDO CORE VARIADA": ["TINTA PARA TECIDO CORES VARIADAS", "Atividades/Convivência"],
  "TINTA PRA CARIMBO": ["TINTA PARA CARIMBO", "Atividades/Convivência"],
  "TINTA PRETA PARA CARIMBO": ["TINTA PARA CARIMBO PRETA", "Atividades/Convivência"],
  "TINTA PVA CORE VARIADA": ["TINTA PVA CORES VARIADAS", "Atividades/Convivência"],
  "TNT": ["TNT", "Atividades/Convivência"],
  "TNT (CORES VARIADAS)": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TNT AMARELO (OFICINA PCF)": ["TNT AMARELO", "Atividades/Convivência"],
  "TNT BRANCO (OFICINA PCF)": ["TNT BRANCO", "Atividades/Convivência"],
  "TNT COLORIDO": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TNT COR AMARELA": ["TNT AMARELO", "Atividades/Convivência"],
  "TNT COR PRETA": ["TNT PRETO", "Atividades/Convivência"],
  "TNT CORE SORTIDA": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TNT CORE VARIADA": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TNT CORE VARIADA (10 M)": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TNT CORES SORTIDAS": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TNT CORES VARIADAS": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TNT CORES VARIADAS (10 M)": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TNT PRETO, AZUL": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TNT VARIADO": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TNT VERDE (OFICINA PCF)": ["TNT VERDE", "Atividades/Convivência"],
  "TNT VERMELHO(OFICINA PCF)": ["TNT VERMELHO", "Atividades/Convivência"],
  "TNT(10 M) COM GLITER CORE AZUL, BRANCO": ["TNT CORES VARIADAS", "Atividades/Convivência"],
  "TOALHA DE MESA": ["TOALHA DE MESA", "Material de Higiene Pessoal"],
  "TOALHA DE PRATO SEM DESENHO": ["PANO DE PRATO", "Material de Higiene Pessoal"],
  "TOALHAS DE MAO": ["TOALHA DE MÃO", "Material de Higiene Pessoal"],
  "TORRADA": ["TORRADA", "Alimentos"],
  "TOUCA": ["TOUCA DESCARTÁVEL", "Material de Higiene Pessoal"],
  "TRIGO": ["FARINHA DE TRIGO", "Alimentos"],
  "TRIGO COM FERMENTO": ["FARINHA DE TRIGO COM FERMENTO", "Alimentos"],
  "TRITURADOR DE PAPEL": ["TRITURADOR DE PAPEL", "Material de Expediente"],
  "VASOURA DE PIASABA": ["VASSOURA DE PIAÇAVA", "Material de Limpeza"],
  "VASSOURA": ["VASSOURA", "Material de Limpeza"],
  "VASSOURA ( URGENTE )": ["VASSOURA", "Material de Limpeza"],
  "VASSOURA DE PIACAVA": ["VASSOURA DE PIAÇAVA", "Material de Limpeza"],
  "VASSOURA DE PIACAVA OU VASCULHAR": ["VASSOURA DE PIAÇAVA", "Material de Limpeza"],
  "VASSOURA DE PLASTICO": ["VASSOURA DE PLÁSTICO", "Material de Limpeza"],
  "VASSOURA ESFREGAO": ["ESFREGÃO", "Material de Limpeza"],
  "VASSOURA MULTIUSO": ["VASSOURA", "Material de Limpeza"],
  "VASSOURAS": ["VASSOURA", "Material de Limpeza"],
  "VEJA": ["LIMPADOR MULTIUSO", "Material de Limpeza"],
  "VEJA LIMPANTE LIMPEZA PESADA": ["LIMPADOR MULTIUSO PESADO", "Material de Limpeza"],
  "VEJA MULTIUSO": ["LIMPADOR MULTIUSO", "Material de Limpeza"],
  "VINAGRE": ["VINAGRE", "Alimentos"],
};

// ── Itens bloqueados (não aparecem na requisição) ──────────
const BLOCKED_ITEMS = new Set([
  "LAMPADA",
  "LAMPADA",
  "LAMPADA LED",
  "LAMPADA LED",
  "LAMPADA",
  "GALAO DE AGUA",
  "GALAO DE AGUA",
  "GALAO DE AGUA",
  "GALAO DE AGUA",
  "REFRIGERANTE",
]);

// ── Regras de split (item correto que na verdade são 2+ itens) ─
const SPLIT_RULES = [
  { corrected: "CANETA AZUL / CANETA PRETA", splits: ["CANETA AZUL", "CANETA PRETA"] },
  { corrected: "CANETA AZUL / CANETA PRETA / CANETA VERMELHA", splits: ["CANETA AZUL", "CANETA PRETA", "CANETA VERMELHA"] },
  { corrected: "CANETA PRETA / CANETA AZUL", splits: ["CANETA PRETA", "CANETA AZUL"] },
  { corrected: "BISCOITO DOCE / BISCOITO AGUA E SAL", splits: ["BISCOITO DOCE", "BISCOITO ÁGUA E SAL"] },
  { corrected: "MARCADOR PERMANENTE AZUL / MARCADOR PERMANENTE PRETO", splits: ["MARCADOR PERMANENTE AZUL", "MARCADOR PERMANENTE PRETO"] },
  { corrected: "MARCADOR PERMANENTE PRETO / MARCADOR PERMANENTE VERMELHO", splits: ["MARCADOR PERMANENTE PRETO", "MARCADOR PERMANENTE VERMELHO"] },
  { corrected: "GUARDANAPO / PAPEL TOALHA", splits: ["GUARDANAPO", "PAPEL TOALHA"] },
  { corrected: "SACO DE LIXO 30L / SACO DE LIXO 50L", splits: ["SACO DE LIXO 30L", "SACO DE LIXO 50L"] },
  { corrected: "SACO DE LIXO 50L / SACO DE LIXO 100L", splits: ["SACO DE LIXO 50L", "SACO DE LIXO 100L"] },
  { corrected: "SACO DE LIXO 30L / 50L / 100L", splits: ["SACO DE LIXO 30L", "SACO DE LIXO 50L", "SACO DE LIXO 100L"] },
];

// ── Regras de escolha obrigatória (genéricos sem especificação) ─
const CHOOSE_RULES = [
  { match: /^LEITE$/i, reason: "Leite genérico — especifique o tipo", options: ["LEITE EM PÓ", "LEITE LÍQUIDO", "LEITE CONDENSADO"] },
  { match: /^SUCO$/i, reason: "Suco genérico — especifique o tipo", options: ["SUCO EM PÓ", "SUCO DE CAIXINHA", "SUCO DE UVA"] },
  { match: /^BALDE$/i, reason: "Balde sem litros — especifique o volume", options: ["BALDE 20L", "BALDE 30L", "BALDE 50L"] },
  { match: /^SACO DE LIXO$/i, reason: "Saco de lixo sem tamanho — especifique o volume", options: ["SACO DE LIXO 15L", "SACO DE LIXO 20L", "SACO DE LIXO 30L", "SACO DE LIXO 50L", "SACO DE LIXO 60L", "SACO DE LIXO 100L", "SACO DE LIXO 200L"] },
  { match: /^CANETA$/i, reason: "Caneta genérica — especifique a cor", options: ["CANETA AZUL", "CANETA PRETA", "CANETA VERMELHA"] },
  { match: /^SABÃO$/i, reason: "Sabão genérico — especifique o tipo", options: ["SABÃO EM PÓ", "SABÃO EM BARRA", "SABÃO EM PEDRA", "SABÃO LÍQUIDO"] },
  { match: /^CLIPS$/i, reason: "Clips sem numeração — especifique o número", options: ["CLIPS Nº 2/0", "CLIPS Nº 3/0", "CLIPS Nº 4/0", "CLIPS Nº 5/0", "CLIPS Nº 6/0", "CLIPS Nº 8/0", "CLIPS Nº 10/0"] },
  { match: /^PASTA$/i, reason: "Pasta genérica — especifique o tipo", options: ["PASTA AZ", "PASTA SANFONADA", "PASTA SUSPENSA", "PASTA POLIONDA", "PASTA ESCARCELA FINA", "PASTA ESCARCELA GROSSA", "PASTA COM ELÁSTICO", "PASTA CATÁLOGO"] },
  { match: /^COPO$/i, reason: "Copo genérico — especifique o uso", options: ["COPO DESCARTÁVEL PARA ÁGUA", "COPO DESCARTÁVEL PARA CAFÉ"] },
  { match: /^TNT$/i, reason: "TNT sem cor — especifique a cor", options: ["TNT AMARELO", "TNT AZUL", "TNT BRANCO", "TNT PRETO", "TNT ROSA", "TNT VERDE", "TNT VERMELHO", "TNT CORES VARIADAS"] },
  { match: /^EVA$/i, reason: "EVA sem cor — especifique a cor", options: ["EVA AMARELO", "EVA AZUL", "EVA BEGE", "EVA BRANCO", "EVA LARANJA", "EVA PRETO", "EVA ROSA", "EVA VERDE", "EVA VERMELHO", "EVA CORES VARIADAS"] },
  { match: /^BALÃO$/i, reason: "Balão sem cor — especifique a cor", options: ["BALÃO AMARELO", "BALÃO AZUL", "BALÃO BRANCO", "BALÃO LARANJA", "BALÃO ROSA", "BALÃO VERDE", "BALÃO VERMELHO", "BALÃO CORES VARIADAS"] },
  { match: /^CARTOLINA$/i, reason: "Cartolina sem cor — especifique a cor", options: ["CARTOLINA AMARELA", "CARTOLINA AZUL", "CARTOLINA BRANCA", "CARTOLINA ROSA", "CARTOLINA VERDE", "CARTOLINA CORES VARIADAS"] },
  { match: /^PAPEL LAMINADO$/i, reason: "Papel laminado sem cor — especifique a cor", options: ["PAPEL LAMINADO DOURADO", "PAPEL LAMINADO PRATA", "PAPEL LAMINADO VERMELHO", "PAPEL LAMINADO VERDE", "PAPEL LAMINADO CORES VARIADAS"] },
  { match: /^TINTA PARA CARIMBO$/i, reason: "Tinta para carimbo sem cor — especifique", options: ["TINTA PARA CARIMBO AZUL", "TINTA PARA CARIMBO PRETA"] },
  { match: /^MARCADOR PERMANENTE$/i, reason: "Marcador permanente sem cor — especifique a cor", options: ["MARCADOR PERMANENTE AZUL", "MARCADOR PERMANENTE PRETO", "MARCADOR PERMANENTE VERMELHO"] },
  { match: /^FITA CETIM$/i, reason: "Fita cetim sem cor — especifique a cor", options: ["FITA CETIM AMARELA", "FITA CETIM AZUL", "FITA CETIM BRANCA", "FITA CETIM ROSA", "FITA CETIM VERDE", "FITA CETIM VERMELHA", "FITA CETIM CORES VARIADAS"] },
  { match: /^FITILHO$/i, reason: "Fitilho sem cor — especifique a cor", options: ["FITILHO AMARELO", "FITILHO AZUL", "FITILHO BRANCO", "FITILHO LARANJA", "FITILHO ROSA", "FITILHO VERDE", "FITILHO VERMELHO", "FITILHO CORES VARIADAS"] },
  { match: /^FUBÁ$/i, reason: "Fubá genérico — especifique o tipo", options: ["FUBÁ DE MILHO", "FUBÁ DE ARROZ"] },
  { match: /^CUSCUZ$/i, reason: "Cuscuz genérico — especifique o tipo", options: ["CUSCUZ DE MILHO", "CUSCUZ DE ARROZ"] },
];

// ── Itens "CORES VARIADAS" válidos (não abrem modal) ───────
const CORES_VARIADAS_OK = new Set([
  "EVA CORES VARIADAS",
  "EVA COM GLITTER CORES VARIADAS",
  "TNT CORES VARIADAS",
  "BALAO CORES VARIADAS",
  "CARTOLINA CORES VARIADAS",
  "PAPEL CREPOM CORES VARIADAS",
  "PAPEL CAMURCA CORES VARIADAS",
  "LA CORES VARIADAS",
  "MICANGAS CORES VARIADAS",
  "MARCA-TEXTO CORES VARIADAS",
  "TINTA PARA TECIDO CORES VARIADAS",
  "TINTA PVA CORES VARIADAS",
  "FELTRO CORES VARIADAS",
  "FITA DECORATIVA CORES VARIADAS",
  "LINHA DE COSTURA CORES VARIADAS",
  "LINHA DE CROCHE CORES VARIADAS",
  "PAPEL CARTAO CORES VARIADAS",
  "PAPEL COLORSET CORES VARIADAS",
  "PAPEL LAMINADO CORES VARIADAS",
]);

// ── Mapa de categorias padrão (nomes canônicos) ────────────
const CATEGORY_ITEMS = {
  "Alimentos": ["ACHOCOLATADO EM PÓ", "AMIDO DE MILHO", "ARROZ", "AVEIA EM FLOCOS", "AÇÚCAR", "AÇÚCAR REFINADO", "BISCOITO DE POLVILHO", "BISCOITO DOCE", "BISCOITO DOCE / BISCOITO ÁGUA E SAL", "BISCOITO MARIA", "BISCOITO RECHEADO", "BISCOITO ÁGUA E SAL", "BOMBOM DE CHOCOLATE", "CAFÉ", "CALABRESA EM LATA", "CANJICA DE MILHO BRANCO", "CARNE ENLATADA", "CHÁ DE CAMOMILA", "CHÁ DE CIDREIRA", "COADOR DE CAFÉ", "CREME DE LEITE", "CREMOGEMA", "CUSCUZ", "CUSCUZ DE ARROZ", "CUSCUZ DE MILHO", "EXTRATO DE TOMATE", "FARINHA BRANCA", "FARINHA DE MILHO", "FARINHA DE TRIGO", "FARINHA DE TRIGO COM FERMENTO", "FARINHA DE TRIGO SEM FERMENTO", "FARINHA LÁCTEA", "FEIJÃO BRANCO", "FEIJÃO CARIOCA", "FEIJÃO PRETO", "FERMENTO", "FLOCÃO DE ARROZ", "FLOCÃO DE MILHO", "FUBÁ", "FUBÁ DE ARROZ", "FUBÁ DE MILHO", "FÉCULA DE BEIJU", "FÉCULA DE MANDIOCA", "FÉCULA DE TAPIOCA", "GARRAFA TÉRMICA DE CAFÉ", "LEITE", "LEITE CONDENSADO", "LEITE EM PÓ", "LEITE EM PÓ INTEGRAL", "LEITE LÍQUIDO", "LEITE LÍQUIDO INTEGRAL", "MACARRÃO", "MACARRÃO ESPAGUETE", "MANTEIGA", "MARGARINA", "MARGARINA COM SAL", "MARGARINA SEM SAL", "MASSA DE CUSCUZ", "MASSA DE TAPIOCA", "MASSA DE TAPIOCA PARA MINGAU", "MASSA PARA MINGAU", "MASSA PRONTA PARA BOLO", "MILHO BRANCO PARA MINGAU", "MILHO PARA MINGAU", "MILHO PARA PIPOCA", "MILHO VERDE EM CONSERVA", "MINGAU DE MILHO", "MINGAU DE TAPIOCA", "MINGAU DE TAPIOCA COM COCO", "MOLHO DE TOMATE", "MUCILON", "OVO", "PÃO DE FORMA", "REQUEIJÃO", "SAL", "SALGADINHOS", "SALSICHA EM LATA", "SARDINHA AO MOLHO DE TOMATE", "SARDINHA AO ÓLEO", "SARDINHA EM LATA", "SUCO", "SUCO DE CAIXINHA", "SUCO DE UVA", "SUCO EM PÓ", "TAPIOCA", "TAPIOCA GROSSA", "TEMPERO SECO EM PÓ", "TORRADA", "VINAGRE", "ÓLEO DE SOJA"],
  "Atividades/Convivência": ["AGULHA DE CROCHÊ", "ALMOFADA DE CARIMBO", "APITO", "BALÃO", "BALÃO AMARELO", "BALÃO AZUL", "BALÃO BRANCO", "BALÃO CORES VARIADAS", "BALÃO LARANJA", "BALÃO VERDE", "BALÃO VERMELHO", "BAMBOLÊ", "BARBANTE", "BASTÃO DE COLA QUENTE", "BOLA DE FUTEBOL DE CAMPO", "BOLA DE FUTSAL", "BOLA DE QUEIMADO", "BOLINHA ANTI-STRESS", "BOLINHA PILATES", "CADERNO DE DESENHO", "CANETINHA HIDROCOR", "CARTOLINA", "CARTOLINA CORES VARIADAS", "CARTOLINA ROSA", "CARTOLINA VERDE", "COLA COM GLITTER", "COLA COM GLITTER DOURADO", "COLA DE ISOPOR", "COLA DE SILICONE", "COLA PARA EVA", "COLA PARA TECIDO", "COLA QUENTE", "EVA", "EVA AMARELO", "EVA AZUL", "EVA BEGE", "EVA BRANCO", "EVA COM GLITTER BRANCO", "EVA COM GLITTER CORES VARIADAS", "EVA COM GLITTER DOURADO", "EVA COM GLITTER PRATA", "EVA COM GLITTER ROSA", "EVA COM GLITTER VERDE", "EVA COM GLITTER VERMELHO", "EVA CORES VARIADAS", "EVA LARANJA", "EVA PRETO", "EVA ROSA", "EVA VERDE", "EVA VERMELHO", "FELTRO CORES VARIADAS", "FIO DE NYLON", "FIO DE SILICONE", "FIO ENCERADO", "FITA CETIM", "FITA CETIM VERDE", "FITA DECORATIVA", "FITA DECORATIVA CORES VARIADAS", "FITILHO", "FITILHO LARANJA", "GIZ DE CERA", "IOIÔ COM LUZES", "JOGO DE ALFABETO", "JOGO DE DAMAS", "JOGO EDUCATIVO", "LANTEJOULA", "LINHA DE COSTURA CORES VARIADAS", "LINHA DE CROCHÊ CORES VARIADAS", "LÁPIS DE COR", "LÃ CORES VARIADAS", "MASSA DE MODELAR", "MIÇANGAS CORES VARIADAS", "PAPEL CAMURÇA AMARELO", "PAPEL CAMURÇA CORES VARIADAS", "PAPEL CAMURÇA LARANJA", "PAPEL COLORSET CORES VARIADAS", "PAPEL CREPOM AMARELO", "PAPEL CREPOM CORES VARIADAS", "PAPEL CRIATIVO", "PAPEL FOTOGRÁFICO", "PAPEL LAMINADO", "PAPEL LAMINADO CORES VARIADAS", "PAPEL LAMINADO VERMELHO", "PAPEL PARA PINTURA", "PINCEL PARA PINTURA", "PINCEL PARA PINTURA GRANDE", "PINCEL PARA PINTURA PEQUENO", "PISTOLA DE COLA QUENTE", "PLACA DE ISOPOR", "TATAME COLORIDO", "TECIDO CHITÃO", "TINTA GUACHE", "TINTA PARA CARIMBO", "TINTA PARA CARIMBO AZUL", "TINTA PARA CARIMBO PRETA", "TINTA PARA TECIDO CORES VARIADAS", "TINTA PVA CORES VARIADAS", "TNT", "TNT AMARELO", "TNT BRANCO", "TNT CORES VARIADAS", "TNT PRETO", "TNT VERDE", "TNT VERMELHO"],
  "Material Descartável": ["COLHER DESCARTÁVEL", "COPO DESCARTÁVEL PARA CAFÉ", "COPO DESCARTÁVEL PARA ÁGUA", "FRALDA DESCARTÁVEL", "FRALDA DESCARTÁVEL ADULTO G", "FRALDA DESCARTÁVEL INFANTIL", "FRALDA DESCARTÁVEL INFANTIL M", "GARFO DESCARTÁVEL", "GUARDANAPO", "GUARDANAPO / PAPEL TOALHA", "LUVA DESCARTÁVEL", "MÁSCARA DESCARTÁVEL", "PALITO DE CHURRASCO", "PALITO DE PICOLE", "PANO DE PRATO", "PRATO DESCARTÁVEL", "PRATO DESCARTÁVEL PARA BOLO", "SACO DE LIXO", "SACO DE LIXO 100L", "SACO DE LIXO 15L", "SACO DE LIXO 200L", "SACO DE LIXO 20L", "SACO DE LIXO 30L", "SACO DE LIXO 30L / 50L / 100L", "SACO DE LIXO 30L / SACO DE LIXO 50L", "SACO DE LIXO 50L", "SACO DE LIXO 50L / SACO DE LIXO 100L", "SACO DE LIXO 60L"],
  "Material de Expediente": ["APAGADOR DE QUADRO BRANCO", "APONTADOR", "BANDEJA PARA PAPEL", "BLOCO DE NOTAS", "BORRACHA", "BORRACHA BICOLOR", "CADEADO", "CADERNO BROCHURA", "CADERNO UNIVERSITÁRIO", "CAIXA ARQUIVO MORTO", "CANETA", "CANETA AZUL", "CANETA AZUL / CANETA PRETA", "CANETA AZUL / CANETA PRETA / CANETA VERMELHA", "CANETA PRETA", "CANETA PRETA / CANETA AZUL", "CANETA VERMELHA", "CAPA DE PROCESSO", "CLIPS", "CLIPS Nº 10/0", "CLIPS Nº 2/0", "CLIPS Nº 3/0", "CLIPS Nº 4/0", "CLIPS Nº 5/0", "CLIPS Nº 6/0", "CLIPS Nº 8/0", "COLA BASTÃO", "COLA BRANCA", "COLA SPRAY", "CORRETIVO", "ENVELOPE", "ENVELOPE A4", "ENVELOPE GRANDE", "ENVELOPE OFÍCIO", "ESCARCELA", "ESCARCELA FINA", "ESCARCELA GROSSA", "ESCARCELA PLÁSTICA", "ESCARCELA PLÁSTICA FINA", "ESTILETE", "ESTILETE LARGO", "ETIQUETA ADESIVA", "ETIQUETA PARA PASTA SUSPENSA", "EXTRATOR DE GRAMPOS", "EXTRATOR DE GRAMPOS TIPO ESPÁTULA", "FITA ADESIVA TRANSPARENTE", "FITA CREPE", "FITA DUPLA FACE", "FITA DUREX", "FITA GOMADA", "FITA GOMADA GROSSA", "FLIP-CHART", "FÓSFORO", "GRAFITE", "GRAMPEADOR", "GRAMPEADOR GRANDE", "GRAMPEADOR MÉDIO", "GRAMPEADOR PEQUENO", "GRAMPO PARA GRAMPEADOR", "GRAMPO PARA GRAMPEADOR 26/6", "GRAMPO PARA GRAMPEADOR Nº 24", "GRAMPO PLÁSTICO", "ISQUEIRO", "LIGA ELÁSTICA", "LIVRO DE ATA", "LIVRO DE ATA FINO", "LIVRO DE ATA GROSSO", "LÁPIS GRAFITE", "LÁPIS GRAFITE Nº 2", "MARCA-TEXTO", "MARCA-TEXTO CORES VARIADAS", "MARCADOR PERMANENTE", "MARCADOR PERMANENTE AZUL", "MARCADOR PERMANENTE AZUL / MARCADOR PERMANENTE PRETO", "MARCADOR PERMANENTE PRETO", "MARCADOR PERMANENTE PRETO / MARCADOR PERMANENTE VERMELHO", "MARCADOR PERMANENTE VERMELHO", "ORGANIZADOR DE DOCUMENTOS", "ORGANIZADOR DE MESA", "PAPEL 40KG PARA CAVALETE", "PAPEL ADESIVO", "PAPEL ALMAÇO", "PAPEL ALUMÍNIO", "PAPEL CARTÃO", "PAPEL CARTÃO CORES VARIADAS", "PAPEL CERTIFICADO", "PAPEL COLORIDO", "PAPEL FILME", "PAPEL PARDO", "PAPEL SEDA", "PAPEL VERGÊ", "PAPEL VERGÊ A4", "PASTA", "PASTA A4", "PASTA AZ", "PASTA AZ 3CM", "PASTA AZ 5CM", "PASTA AZ OFÍCIO", "PASTA CATÁLOGO", "PASTA COM ELÁSTICO", "PASTA COM ELÁSTICO A4", "PASTA COM GRAMPO TRILHO", "PASTA DE DOCUMENTOS", "PASTA ESCARCELA", "PASTA ESCARCELA FINA", "PASTA ESCARCELA GRANDE", "PASTA ESCARCELA GROSSA", "PASTA ESCARCELA PEQUENA", "PASTA L A4", "PASTA PARA ARQUIVO MORTO", "PASTA PLÁSTICA", "PASTA PLÁSTICA GRANDE", "PASTA PLÁSTICA PEQUENA", "PASTA POLIONDA", "PASTA POLIONDA COM ELÁSTICO", "PASTA SANFONADA", "PASTA SANFONADA A4", "PASTA SUSPENSA", "PEN DRIVE", "PERCEVEJO PARA MURAL", "PERFURADOR", "PERFURADOR MÉDIO", "PERFURADOR PEQUENO", "PILHA AAA", "PINCEL ATÔMICO", "PINCEL ATÔMICO GROSSO", "PINCEL Nº 10", "PINCEL Nº 20", "PINCEL Nº 30", "PINCEL PARA QUADRO BRANCO", "PINCEL PARA QUADRO BRANCO AZUL", "PORTA DOCUMENTOS", "PORTA-CANETAS", "PORTA-LÁPIS", "POST-IT", "POST-IT GRANDE", "PRANCHETA", "PRANCHETA A4", "QUADRO BRANCO", "RESMA DE PAPEL A4", "RESMA DE PAPEL A4 COLORIDO", "RÉGUA", "SACO PLÁSTICO A4", "SUPORTE PARA FITA ADESIVA", "TESOURA", "TESOURA DE PICOTE", "TESOURA GRANDE", "TESOURA PEQUENA", "TRITURADOR DE PAPEL"],
  "Material de Higiene Pessoal": ["ABSORVENTE", "CREME DENTAL", "DISPENSER DE SABONETE", "MÁSCARA DESCARTÁVEL", "PANO DE PRATO", "PAPEL HIGIÊNICO", "PAPEL TOALHA", "PORTA PAPEL TOALHA", "PROTETOR FACIAL", "SABONETE EM BARRA", "SABONETE LÍQUIDO", "TOALHA DE MESA", "TOALHA DE MÃO", "TOUCA DESCARTÁVEL"],
  "Material de Limpeza": ["AVENTAL PLÁSTICO", "BALDE", "BALDE 20L", "BALDE 30L", "BALDE 50L", "BOM AR", "CESTO DE LIXO", "CESTO DE LIXO COM PEDAL", "CESTO DE LIXO COM TAMPA", "CESTO DE LIXO GRANDE", "CESTO DE LIXO PEQUENO", "COLA DE CONTATO", "COLA DE CONTATO (BRASCOLA)", "DESENGRAXANTE", "DESINFETANTE", "DESINFETANTE PARA CHÃO", "DETERGENTE LAVA-LOUÇA", "DETERGENTE MULTIUSO", "ESCOVA DE LAVAR", "ESCOVA SANITÁRIA", "ESCOVÃO", "ESFREGÃO", "ESPANADOR", "ESPONJA DE LAVAR LOUÇA", "ESPONJA DUPLA FACE", "FLANELA", "INSETICIDA", "LIMPA-ALUMÍNIO", "LIMPA-VIDRO", "LIMPADOR MULTIUSO", "LIMPADOR MULTIUSO PESADO", "LUBRIFICANTE", "LUSTRA-MÓVEIS", "LUVA DE BORRACHA", "LUVA DE BORRACHA CANO LONGO", "LUVA DE BORRACHA TAMANHO G", "LUVA DE BORRACHA TAMANHO M", "LUVA DE LÁTEX", "LUVA PVC TAMANHO P", "MOP GIRATÓRIO", "PALHA DE AÇO", "PANO DE CHÃO", "PANO DE PIA", "PANO MULTIUSO", "PEDRA SANITÁRIA", "PORTA SABÃO", "PÁ DE LIXO", "RODO", "RODO GRANDE", "SABÃO EM BARRA", "SABÃO EM PEDRA", "SABÃO EM PÓ", "SABÃO LÍQUIDO", "SUPER BONDER", "VASSOURA", "VASSOURA DE PIAÇAVA", "VASSOURA DE PLÁSTICO", "ÁGUA SANITÁRIA", "ÁLCOOL EM GEL", "ÁLCOOL EM GEL 70%", "ÁLCOOL LÍQUIDO", "ÁLCOOL LÍQUIDO 70%"],
};

// ── Mapa de categorias antigas → padrão ────────────────────
const CATEGORY_ALIASES = {
  "ALIMENTICIO": "Alimentos",
  "ALIMENTO": "Alimentos",
  "ALIMENTO PERECIVEL": "Alimentos",
  "ALIMENTOS": "Alimentos",
  "ATIVIDADES": "Atividades/Convivência",
  "CEREAIS/GRAOS/AMIDO": "Alimentos",
  "DESCARTAVEL": "Material Descartável",
  "ENLATADOS": "Alimentos",
  "EXPEDIENTE": "Material de Expediente",
  "HIGIENE": "Material de Higiene Pessoal",
  "HIGIENE E LIMPEZA": "Material de Limpeza",
  "HIGIENE PESSOAL": "Material de Higiene Pessoal",
  "ITENS": "Material de Expediente",
  "LANCHE PARA O SCFV.": "Alimentos",
  "LANCHE PARA SCFV": "Alimentos",
  "LIMPEZA": "Material de Limpeza",
  "MATERIAIS": "Alimentos",
  "MATERIAL DE CONSUMO": "Alimentos",
  "MATERIAL DE ESCRITORIO": "Material de Expediente",
  "MATERIAL DE USO HIGIENICO": "Material de Higiene Pessoal",
  "MATERIAL PARA CONSUMO": "Alimentos",
  "MATERIAL PARA CONSUMO 16/04/2026": "Alimentos",
  "OUTROS": "Material de Expediente",
  "OUTROS ITENS": "Material de Expediente",
  "PROCESSADOS E INDUSTRIALIZADOS": "Alimentos",
  "SCFV": "Alimentos",
};


// ═══════════════════════════════════════════════════════════════════
// FUNÇÕES PRINCIPAIS — Sem Firebase
// ═══════════════════════════════════════════════════════════════════

/**
 * Resolve o nome canônico e categoria de um item pelo nome original.
 * Retorna { nome, categoria, found } sem nenhuma chamada ao Firebase.
 */
function resolveItem(rawName) {
  if (!rawName) return { nome: rawName, categoria: null, found: false };
  const key = _rmac(rawName);

  // 1. Bloqueado?
  if (BLOCKED_ITEMS.has(key)) {
    return { nome: rawName, categoria: null, found: true, blocked: true,
      reason: "Este item não pode ser requisitado pelo almoxarifado." };
  }

  // 2. Alias direto?
  const alias = ITEMS_ALIASES[key];
  if (alias) return { nome: alias[0], categoria: alias[1], found: true };

  // 3. Busca parcial (nome contido no alias)
  for (const [k, [nome, cat]] of Object.entries(ITEMS_ALIASES)) {
    if (k.length >= 5 && key.startsWith(k)) {
      return { nome, categoria: cat, found: true, partial: true };
    }
  }

  return { nome: rawName, categoria: null, found: false };
}

/**
 * Resolve o nome canônico de uma categoria.
 */
function resolveCategoria(rawCat) {
  if (!rawCat) return null;
  const key = _rmac(rawCat);
  return CATEGORY_ALIASES[key] || rawCat;
}

/**
 * Verifica se um item (já com nome correto) precisa ser dividido em 2+.
 * Retorna array de splits ou null.
 */
function checkSplit(correctedName) {
  const key = _rmac(correctedName);
  const rule = SPLIT_RULES.find(r => _rmac(r.corrected) === key);
  return rule ? rule.splits : null;
}

/**
 * Verifica se um item (já com nome correto) precisa de escolha obrigatória.
 * Retorna a regra ou null.
 */
function checkChoose(correctedName) {
  return CHOOSE_RULES.find(r => r.match.test(correctedName)) || null;
}

/**
 * Verifica se um item é um "CORES VARIADAS" válido (não precisa modal).
 */
function isCoresVariadasOk(correctedName) {
  return CORES_VARIADAS_OK.has(_rmac(correctedName));
}

/**
 * Pipeline completo: recebe nome bruto → retorna objeto com todas as decisões.
 * Usado pelo modal-revisao-itens.js SEM Firebase.
 */
function analisarItem(rawName, unidade) {
  const resolved = resolveItem(rawName);

  if (resolved.blocked) {
    return { type: "blocked", original: rawName, reason: resolved.reason };
  }

  const corrected = resolved.nome;
  const categoria = resolved.categoria;

  // Verifica split
  const splits = checkSplit(corrected);
  if (splits) {
    return { type: "split", original: rawName, corrected, categoria, splits };
  }

  // Verifica escolha obrigatória
  const chooseRule = checkChoose(corrected);
  if (chooseRule) {
    return { type: "choose", original: rawName, corrected, categoria,
      reason: chooseRule.reason, options: chooseRule.options };
  }

  // Verifica se é genérico de cor (TNT, EVA, etc.) que não é CORES VARIADAS
  if (/CORES VARIADAS/i.test(corrected) && !isCoresVariadasOk(corrected)) {
    return { type: "choose", original: rawName, corrected, categoria,
      reason: "Especifique a cor", options: [] };
  }

  // Nome mudou? → rename
  if (resolved.found && _rmac(corrected) !== _rmac(rawName)) {
    return { type: "rename", original: rawName, corrected, categoria };
  }

  // Tudo OK
  return { type: "ok", original: rawName, corrected, categoria };
}

export {
  ITEMS_ALIASES, BLOCKED_ITEMS, SPLIT_RULES, CHOOSE_RULES,
  CORES_VARIADAS_OK, CATEGORY_ITEMS, CATEGORY_ALIASES,
  resolveItem, resolveCategoria, checkSplit, checkChoose,
  isCoresVariadasOk, analisarItem
};
